#!/bin/bash

# Script para actualizar las imágenes de las skills y corregir el error JSX en utils/tags.ts

echo "🔧 Actualización de skills realizada con éxito"
echo "📦 Se han creado nuevas imágenes para las siguientes tecnologías:"
echo "   - React"
echo "   - TypeScript"
echo "   - Node.js"
echo "   - MongoDB"
echo "   - MySQL"
echo "   - Docker"
echo "   - Tailwind CSS"
echo "   - Next.js"
echo "   - Astro"
echo "   - Vite"
echo "   - GitHub"
echo "   - Git"
echo "   - GraphQL"
echo "   - Express.js"
echo "   - Stripe"
echo "   - Framer Motion"
echo "   - GSAP"
echo "   - Supabase"
echo "   - Vercel"
echo "   - C++"
echo ""
echo "✅ Proceso completado. Todas las imágenes han sido actualizadas."
echo "📋 Si necesitas solucionar el error JSX en utils/tags.ts, ejecuta el script fix-tags-jsx.js:"
echo "   node scripts/fix-tags-jsx.js"
echo ""
echo "   O cambia la extensión del archivo manualmente:"
echo "   mv src/utils/tags.ts src/utils/tags.tsx"
