// Archivo de configuración central para las descripciones de las skills - Parte 4
// Múltiples idiomas soportados

  'MySQL': {
    es: 'Sistema de gestión de bases de datos relacional de código abierto. Ampliamente utilizado en aplicaciones web para almacenamiento estructurado de datos.',
    en: 'Open-source relational database management system. Widely used in web applications for structured data storage.',
    'en-us': 'Open-source relational database management system. Widely used in web applications for structured data storage.',
    'es-mx': 'Sistema de gestión de bases de datos relacional de código abierto. Ampliamente utilizado en aplicaciones web para almacenamiento estructurado de datos.',
    pt: 'Sistema de gerenciamento de banco de dados relacional de código aberto. Amplamente utilizado em aplicações web para armazenamento estruturado de dados.',
    fr: 'Système de gestion de base de données relationnelle open-source. Largement utilisé dans les applications web pour le stockage structuré de données.',
    de: 'Open-Source-Relationales Datenbankmanagementsystem. Weit verbreitet in Webanwendungen für strukturierte Datenspeicherung.',
    it: 'Sistema di gestione di database relazionali open source. Ampiamente utilizzato nelle applicazioni web per l\'archiviazione strutturata dei dati.',
    zh: '开源关系数据库管理系统。广泛用于 Web 应用程序的结构化数据存储。',
    ja: 'オープンソースのリレーショナルデータベース管理システム。構造化データストレージのためにWebアプリケーションで広く使用されています。',
    ru: 'Система управления реляционными базами данных с открытым исходным кодом. Широко используется в веб-приложениях для структурированного хранения данных.',
    ar: 'نظام إدارة قواعد البيانات العلائقية مفتوح المصدر. يستخدم على نطاق واسع في تطبيقات الويب للتخزين المنظم للبيانات.',
    hi: 'ओपन-सोर्स रिलेशनल डेटाबेस मैनेजमेंट सिस्टम। संरचित डेटा स्टोरेज के लिए वेब एप्लिकेशन में व्यापक रूप से उपयोग किया जाता है।',
    ko: '오픈 소스 관계형 데이터베이스 관리 시스템. 구조화된 데이터 저장을 위해 웹 애플리케이션에서 널리 사용됩니다.',
    nl: 'Open-source relationeel databasemanagementsysteem. Veel gebruikt in webapplicaties voor gestructureerde dataopslag.',
    pl: 'System zarządzania relacyjnymi bazami danych o otwartym kodzie źródłowym. Szeroko stosowany w aplikacjach internetowych do przechowywania ustrukturyzowanych danych.',
    tr: 'Açık kaynaklı ilişkisel veritabanı yönetim sistemi. Yapılandırılmış veri depolama için web uygulamalarında yaygın olarak kullanılır.',
    hv: 'Tubis aōghar gundyton āeksiā ānogar. Ampa udra hen gaomilaksir tubisy sikagion aōghar.'
  },
  'Strapi': {
    es: 'Sistema de gestión de contenido (CMS) headless de código abierto. Permite construir APIs rápidamente con una interfaz de administración personalizable.',
    en: 'Open-source headless content management system (CMS). Allows building APIs quickly with a customizable admin interface.',
    'en-us': 'Open-source headless content management system (CMS). Allows building APIs quickly with a customizable admin interface.',
    'es-mx': 'Sistema de gestión de contenido (CMS) headless de código abierto. Permite construir APIs rápidamente con una interfaz de administración personalizable.',
    pt: 'Sistema de gerenciamento de conteúdo headless (CMS) de código aberto. Permite construir APIs rapidamente com uma interface de administração personalizável.',
    fr: 'Système de gestion de contenu (CMS) headless open-source. Permet de construire des API rapidement avec une interface d\'administration personnalisable.',
    de: 'Open-Source-Headless-Content-Management-System (CMS). Ermöglicht die schnelle Erstellung von APIs mit einer anpassbaren Admin-Oberfläche.',
    it: 'Sistema di gestione dei contenuti (CMS) headless open source. Consente di creare API rapidamente con un\'interfaccia di amministrazione personalizzabile.',
    zh: '开源无头内容管理系统 (CMS)。允许使用可自定义的管理界面快速构建 API。',
    ja: 'オープンソースのヘッドレスコンテンツ管理システム（CMS）。カスタマイズ可能な管理インターフェースでAPIを迅速に構築できます。',
    ru: 'Система управления контентом (CMS) без интерфейса с открытым исходным кодом. Позволяет быстро создавать API с настраиваемым интерфейсом администратора.',
    ar: 'نظام إدارة محتوى بدون واجهة (CMS) مفتوح المصدر. يسمح ببناء واجهات برمجة التطبيقات بسرعة مع واجهة إدارة قابلة للتخصيص.',
    hi: 'ओपन-सोर्स हेडलेस कंटेंट मैनेजमेंट सिस्टम (CMS)। अनुकूलन योग्य एडमिन इंटरफेस के साथ तेज़ी से APIs बनाने की अनुमति देता है।',
    ko: '오픈 소스 헤드리스 콘텐츠 관리 시스템(CMS). 사용자 정의 가능한 관리 인터페이스로 API를 빠르게 구축할 수 있습니다.',
    nl: 'Open-source headless content management systeem (CMS). Maakt het mogelijk om snel API\'s te bouwen met een aanpasbare beheerdersinterface.',
    pl: 'Otwarte źródło bezgłowego systemu zarządzania treścią (CMS). Umożliwia szybkie tworzenie API z konfigurowalnym interfejsem administratora.',
    tr: 'Açık kaynaklı başsız içerik yönetim sistemi (CMS). Özelleştirilebilir bir yönetici arayüzü ile hızlı bir şekilde API\'ler oluşturmaya olanak tanır.',
    hv: 'Tubis aōghar mazvȳti āeksiā gundyton. Sikagon vestragon apis mazōrety yn uēpa pōja.'
  },
  'C++': {
    es: 'Lenguaje de programación de propósito general con características de bajo nivel. Utilizado en aplicaciones de alto rendimiento, videojuegos, sistemas embebidos y más.',
    en: 'General-purpose programming language with low-level features. Used in high-performance applications, video games, embedded systems, and more.',
    'en-us': 'General-purpose programming language with low-level features. Used in high-performance applications, video games, embedded systems, and more.',
    'es-mx': 'Lenguaje de programación de propósito general con características de bajo nivel. Utilizado en aplicaciones de alto rendimiento, videojuegos, sistemas embebidos y más.',
    pt: 'Linguagem de programação de propósito geral com recursos de baixo nível. Usada em aplicações de alto desempenho, jogos, sistemas embarcados e mais.',
    fr: 'Langage de programmation à usage général avec des fonctionnalités de bas niveau. Utilisé dans les applications haute performance, les jeux vidéo, les systèmes embarqués et plus encore.',
    de: 'Allzweck-Programmiersprache mit Low-Level-Funktionen. Wird in Hochleistungsanwendungen, Videospielen, eingebetteten Systemen und mehr verwendet.',
    it: 'Linguaggio di programmazione general-purpose con funzionalità di basso livello. Utilizzato in applicazioni ad alte prestazioni, videogiochi, sistemi embedded e altro.',
    zh: '具有低级功能的通用编程语言。用于高性能应用程序、视频游戏、嵌入式系统等。',
    ja: '低レベル機能を備えた汎用プログラミング言語。高性能アプリケーション、ビデオゲーム、組み込みシステムなどで使用されます。',
    ru: 'Язык программирования общего назначения с низкоуровневыми функциями. Используется в высокопроизводительных приложениях, видеоиграх, встроенных системах и многом другом.',
    ar: 'لغة برمجة للأغراض العامة مع ميزات منخفضة المستوى. تستخدم في التطبيقات عالية الأداء وألعاب الفيديو والأنظمة المدمجة والمزيد.',
    hi: 'लो-लेवल फीचर्स वाली जनरल-परपस प्रोग्रामिंग भाषा। हाई-परफॉर्मेंस एप्लिकेशन, वीडियोगेम, एम्बेडेड सिस्टम और अधिक में उपयोग किया जाता है।',
    ko: '저수준 기능을 갖춘 범용 프로그래밍 언어. 고성능 애플리케이션, 비디오 게임, 임베디드 시스템 등에 사용됩니다.',
    nl: 'Algemene programmeertaal met low-level functies. Gebruikt in high-performance applicaties, videogames, embedded systems en meer.',
    pl: 'Język programowania ogólnego przeznaczenia z funkcjami niskopoziomowymi. Używany w aplikacjach o wysokiej wydajności, grach wideo, systemach wbudowanych i innych.',
    tr: 'Düşük seviyeli özelliklere sahip genel amaçlı programlama dili. Yüksek performanslı uygulamalarda, video oyunlarında, gömülü sistemlerde ve daha fazlasında kullanılır.',
    hv: 'Kodātyr mirros morghon yn lanti pōnta. Udra hen mazōrety gaomilankon, lynoty, embedy tubisy, se tolmiot.'
  },
  'Phaser': {
    es: 'Framework para crear juegos HTML5 para navegadores móviles y de escritorio. Soporta Canvas y WebGL, con física, animaciones y gestión de assets.',
    en: 'Framework for creating HTML5 games for desktop and mobile browsers. Supports Canvas and WebGL, with physics, animations, and asset management.',
    'en-us': 'Framework for creating HTML5 games for desktop and mobile browsers. Supports Canvas and WebGL, with physics, animations, and asset management.',
    'es-mx': 'Framework para crear juegos HTML5 para navegadores móviles y de escritorio. Soporta Canvas y WebGL, con física, animaciones y gestión de assets.',
    pt: 'Framework para criar jogos HTML5 para navegadores desktop e móveis. Suporta Canvas e WebGL, com física, animações e gerenciamento de assets.',
    fr: 'Framework pour créer des jeux HTML5 pour navigateurs de bureau et mobiles. Prend en charge Canvas et WebGL, avec physique, animations et gestion des assets.',
    de: 'Framework zum Erstellen von HTML5-Spielen für Desktop- und Mobile-Browser. Unterstützt Canvas und WebGL, mit Physik, Animationen und Asset-Management.',
    it: 'Framework per creare giochi HTML5 per browser desktop e mobili. Supporta Canvas e WebGL, con fisica, animazioni e gestione degli asset.',
    zh: '用于为桌面和移动浏览器创建 HTML5 游戏的框架。支持 Canvas 和 WebGL，具有物理引擎、动画和资产管理功能。',
    ja: 'デスクトップおよびモバイルブラウザ向けのHTML5ゲームを作成するためのフレームワーク。物理演算、アニメーション、アセット管理を備えたCanvasとWebGLをサポートします。',
    ru: 'Фреймворк для создания HTML5-игр для настольных и мобильных браузеров. Поддерживает Canvas и WebGL, с физикой, анимацией и управлением ресурсами.',
    ar: 'إطار عمل لإنشاء ألعاب HTML5 للمتصفحات المكتبية والمحمولة. يدعم Canvas و WebGL، مع الفيزياء والرسوم المتحركة وإدارة الأصول.',
    hi: 'डेस्कटॉप और मोबाइल ब्राउज़र के लिए HTML5 गेम बनाने के लिए फ्रेमवर्क। Canvas और WebGL का समर्थन करता है, फिजिक्स, एनिमेशन और एसेट मैनेजमेंट के साथ।',
    ko: '데스크톱 및 모바일 브라우저용 HTML5 게임을 만들기 위한 프레임워크. 물리, 애니메이션 및 자산 관리 기능이 포함된 Canvas 및 WebGL을 지원합니다.',
    nl: 'Framework voor het maken van HTML5-games voor desktop- en mobiele browsers. Ondersteunt Canvas en WebGL, met fysica, animaties en assetbeheer.',
    pl: 'Framework do tworzenia gier HTML5 dla przeglądarek stacjonarnych i mobilnych. Obsługuje Canvas i WebGL, z fizyką, animacjami i zarządzaniem zasobami.',
    tr: 'Masaüstü ve mobil tarayıcılar için HTML5 oyunları oluşturmaya yönelik framework. Fizik, animasyonlar ve varlık yönetimi ile Canvas ve WebGL\'i destekler.',
    hv: 'Zyhossyr vestragon HTML5 lynoty hen dohaerza se portal mirehī. Iksā Canvas se WebGL, yn physika, animagon, se glaeson gundyton.'
  },
  'Vercel': {
    es: 'Plataforma en la nube para despliegue de aplicaciones frontend y APIs sin servidor. Optimizada para frameworks modernos como Next.js, con despliegue automático desde Git.',
    en: 'Cloud platform for deploying frontend applications and serverless APIs. Optimized for modern frameworks like Next.js, with automatic deployment from Git.',
    'en-us': 'Cloud platform for deploying frontend applications and serverless APIs. Optimized for modern frameworks like Next.js, with automatic deployment from Git.',
    'es-mx': 'Plataforma en la nube para despliegue de aplicaciones frontend y APIs sin servidor. Optimizada para frameworks modernos como Next.js, con despliegue automático desde Git.',
    pt: 'Plataforma em nuvem para implantação de aplicações frontend e APIs serverless. Otimizada para frameworks modernos como Next.js, com implantação automática a partir do Git.',
    fr: 'Plateforme cloud pour le déploiement d\'applications frontend et d\'API serverless. Optimisée pour les frameworks modernes comme Next.js, avec déploiement automatique à partir de Git.',
    de: 'Cloud-Plattform für die Bereitstellung von Frontend-Anwendungen und serverlosen APIs. Optimiert für moderne Frameworks wie Next.js, mit automatischer Bereitstellung aus Git.',
    it: 'Piattaforma cloud per il deployment di applicazioni frontend e API serverless. Ottimizzata per framework moderni come Next.js, con deployment automatico da Git.',
    zh: '用于部署前端应用程序和无服务器 API 的云平台。针对 Next.js 等现代框架进行了优化，支持从 Git 自动部署。',
    ja: 'フロントエンドアプリケーションとサーバーレスAPIをデプロイするためのクラウドプラットフォーム。Next.jsなどの最新フレームワーク向けに最適化され、Gitからの自動デプロイが可能です。',
    ru: 'Облачная платформа для развертывания фронтенд-приложений и бессерверных API. Оптимизирована для современных фреймворков, таких как Next.js, с автоматическим развертыванием из Git.',
    ar: 'منصة سحابية لنشر تطبيقات الواجهة الأمامية وواجهات برمجة التطبيقات بدون خادم. محسنة للأطر الحديثة مثل Next.js، مع نشر تلقائي من Git.',
    hi: 'फ्रंटएंड एप्लिकेशन और सर्वरलेस APIs को डिप्लॉय करने के लिए क्लाउड प्लेटफॉर्म। Next.js जैसे आधुनिक फ्रेमवर्क के लिए अनुकूलित, Git से स्वचालित डिप्लॉयमेंट के साथ।',
    ko: '프론트엔드 애플리케이션 및 서버리스 API를 배포하기 위한 클라우드 플랫폼. Next.js와 같은 최신 프레임워크에 최적화되어 있으며 Git에서 자동 배포됩니다.',
    nl: 'Cloudplatform voor het implementeren van frontend-applicaties en serverloze API\'s. Geoptimaliseerd voor moderne frameworks zoals Next.js, met automatische implementatie vanuit Git.',
    pl: 'Platforma chmurowa do wdrażania aplikacji frontendowych i bezserwerowych API. Zoptymalizowana dla nowoczesnych frameworków, takich jak Next.js, z automatycznym wdrażaniem z Gita.',
    tr: 'Frontend uygulamaları ve sunucusuz API\'leri dağıtmak için bulut platformu. Git\'ten otomatik dağıtım ile Next.js gibi modern çerçeveler için optimize edilmiştir.',
    hv: 'Tubir urnen qrinuntys gaomilaksiry se apis kostōbi. Jenigon uēpa lanta zyhossyr mirre Next.js, yn automāzma urnen Git.'
  },
  'NPM': {
    es: 'Gestor de paquetes para JavaScript. La mayor biblioteca de software del mundo, con más de un millón de paquetes para aplicaciones web modernas.',
    en: 'Package manager for JavaScript. The world\'s largest software library, with over a million packages for modern web applications.',
    'en-us': 'Package manager for JavaScript. The world\'s largest software library, with over a million packages for modern web applications.',
    'es-mx': 'Gestor de paquetes para JavaScript. La mayor biblioteca de software del mundo, con más de un millón de paquetes para aplicaciones web modernas.',
    pt: 'Gerenciador de pacotes para JavaScript. A maior biblioteca de software do mundo, com mais de um milhão de pacotes para aplicações web modernas.',
    fr: 'Gestionnaire de paquets pour JavaScript. La plus grande bibliothèque de logiciels au monde, avec plus d\'un million de paquets pour les applications web modernes.',
    de: 'Paketmanager für JavaScript. Die weltweit größte Software-Bibliothek mit über einer Million Paketen für moderne Webanwendungen.',
    it: 'Gestore di pacchetti per JavaScript. La più grande libreria software al mondo, con oltre un milione di pacchetti per applicazioni web moderne.',
    zh: 'JavaScript 的包管理器。世界上最大的软件库，拥有超过一百万个用于现代 Web 应用程序的包。',
    ja: 'JavaScriptのパッケージマネージャー。現代のWebアプリケーション向けに100万を超えるパッケージを提供する世界最大のソフトウェアライブラリ。',
    ru: 'Менеджер пакетов для JavaScript. Крупнейшая в мире библиотека программного обеспечения с более чем миллионом пакетов для современных веб-приложений.',
    ar: 'مدير حزم لـ JavaScript. أكبر مكتبة برمجيات في العالم، مع أكثر من مليون حزمة للتطبيقات الويب الحديثة.',
    hi: 'JavaScript के लिए पैकेज मैनेजर। दुनिया की सबसे बड़ी सॉफ्टवेयर लाइब्रेरी, आधुनिक वेब एप्लिकेशन के लिए एक मिलियन से अधिक पैकेज के साथ।',
    ko: 'JavaScript용 패키지 관리자. 현대 웹 애플리케이션을 위한 백만 개 이상의 패키지가 있는 세계 최대의 소프트웨어 라이브러리.',
    nl: 'Pakketbeheerder voor JavaScript. \'s Werelds grootste softwarebibliotheek, met meer dan een miljoen pakketten voor moderne webapplicaties.',
    pl: 'Menedżer pakietów dla JavaScript. Największa na świecie biblioteka oprogramowania, z ponad milionem pakietów do nowoczesnych aplikacji internetowych.',
    tr: 'JavaScript için paket yöneticisi. Modern web uygulamaları için bir milyondan fazla paket içeren dünyanın en büyük yazılım kütüphanesi.',
    hv: 'Tubis gundyton hen JavaScript. Vējes kȳvana tubis ubrardy, yn tolma mirri rūsy hen lanta gaomilaksir.'
  },
  'PNPM': {
    es: 'Gestor de paquetes rápido y eficiente para JavaScript. Ahorra espacio en disco al usar almacenamiento compartido para dependencias y ofrece rendimiento mejorado.',
    en: 'Fast and efficient package manager for JavaScript. Saves disk space by using shared storage for dependencies and offers improved performance.',
    'en-us': 'Fast and efficient package manager for JavaScript. Saves disk space by using shared storage for dependencies and offers improved performance.',
    'es-mx': 'Gestor de paquetes rápido y eficiente para JavaScript. Ahorra espacio en disco al usar almacenamiento compartido para dependencias y ofrece rendimiento mejorado.',
    pt: 'Gerenciador de pacotes rápido e eficiente para JavaScript. Economiza espaço em disco usando armazenamento compartilhado para dependências e oferece desempenho aprimorado.',
    fr: 'Gestionnaire de paquets rapide et efficace pour JavaScript. Économise de l\'espace disque en utilisant un stockage partagé pour les dépendances et offre des performances améliorées.',
    de: 'Schneller und effizienter Paketmanager für JavaScript. Spart Festplattenspeicher durch gemeinsame Speicherung von Abhängigkeiten und bietet verbesserte Leistung.',
    it: 'Gestore di pacchetti veloce ed efficiente per JavaScript. Risparmia spazio su disco utilizzando l\'archiviazione condivisa per le dipendenze e offre prestazioni migliorate.',
    zh: '快速高效的 JavaScript 包管理器。通过为依赖项使用共享存储来节省磁盘空间，并提供改进的性能。',
    ja: 'JavaScriptのための高速で効率的なパッケージマネージャー。依存関係に共有ストレージを使用してディスク容量を節約し、パフォーマンスを向上させます。',
    ru: 'Быстрый и эффективный менеджер пакетов для JavaScript. Экономит дисковое пространство за счет использования общего хранилища для зависимостей и предлагает улучшенную производительность.',
    ar: 'مدير حزم سريع وفعال لـ JavaScript. يوفر مساحة القرص باستخدام التخزين المشترك للتبعيات ويقدم أداءً محسنًا.',
    hi: 'JavaScript के लिए तेज़ और कुशल पैकेज मैनेजर। निर्भरताओं के लिए साझा स्टोरेज का उपयोग करके डिस्क स्पेस बचाता है और बेहतर प्रदर्शन प्रदान करता है।',
    ko: 'JavaScript용 빠르고 효율적인 패키지 관리자. 종속성에 대해 공유 스토리지를 사용하여 디스크 공간을 절약하고 향상된 성능을 제공합니다.',
    nl: 'Snelle en efficiënte pakketbeheerder voor JavaScript. Bespaart schijfruimte door gedeelde opslag voor afhankelijkheden te gebruiken en biedt verbeterde prestaties.',
    pl: 'Szybki i wydajny menedżer pakietów dla JavaScript. Oszczędza miejsce na dysku, używając współdzielonego magazynu dla zależności i oferuje ulepszoną wydajność.',
    tr: 'JavaScript için hızlı ve verimli paket yöneticisi. Bağımlılıklar için paylaşılan depolama kullanarak disk alanından tasarruf sağlar ve geliştirilmiş performans sunar.',
    hv: 'Tubis gundyton mazōrety se mazōlik hen JavaScript. Zevon tubis āeksiā aōghar sikagon un pōja tubisy hen tubiry.'
  },
  'Debian': {
    es: 'Sistema operativo Linux libre y de código abierto. Conocido por su estabilidad, compromiso con el software libre y amplia compatibilidad con hardware.',
    en: 'Free and open-source Linux operating system. Known for its stability, commitment to free software, and extensive hardware compatibility.',
    'en-us': 'Free and open-source Linux operating system. Known for its stability, commitment to free software, and extensive hardware compatibility.',
    'es-mx': 'Sistema operativo Linux libre y de código abierto. Conocido por su estabilidad, compromiso con el software libre y amplia compatibilidad con hardware.',
    pt: 'Sistema operacional Linux livre e de código aberto. Conhecido por sua estabilidade, compromisso com software livre e ampla compatibilidade de hardware.',
    fr: 'Système d\'exploitation Linux libre et open-source. Connu pour sa stabilité, son engagement envers les logiciels libres et sa large compatibilité matérielle.',
    de: 'Freies und Open-Source-Linux-Betriebssystem. Bekannt für seine Stabilität, Engagement für freie Software und umfangreiche Hardware-Kompatibilität.',
    it: 'Sistema operativo Linux libero e open source. Noto per la sua stabilità, l\'impegno per il software libero e l\'ampia compatibilità hardware.',
    zh: '自由开源的 Linux 操作系统。以其稳定性、对自由软件的承诺和广泛的硬件兼容性而闻名。',
    ja: '自由でオープンソースのLinuxオペレーティングシステム。その安定性、フリーソフトウェアへのコミットメント、幅広いハードウェア互換性で知られています。',
    ru: 'Свободная операционная система Linux с открытым исходным кодом. Известна своей стабильностью, приверженностью свободному программному обеспечению и широкой совместимостью с оборудованием.',
    ar: 'نظام تشغيل Linux مجاني ومفتوح المصدر. معروف باستقراره والتزامه بالبرمجيات الحرة وتوافق الأجهزة الواسع.',
    hi: 'फ्री और ओपन-सोर्स लिनक्स ऑपरेटिंग सिस्टम। अपनी स्थिरता, फ्री सॉफ्टवेयर के प्रति प्रतिबद्धता और व्यापक हार्डवेयर संगतता के लिए जाना जाता है।',
    ko: '무료 및 오픈 소스 Linux 운영 체제. 안정성, 자유 소프트웨어에 대한 헌신 및 광범위한 하드웨어 호환성으로 알려져 있습니다.',
    nl: 'Vrij en open-source Linux-besturingssysteem. Bekend om zijn stabiliteit, toewijding aan vrije software en uitgebreide hardwarecompatibiliteit.',
    pl: 'Darmowy i otwartoźródłowy system operacyjny Linux. Znany ze swojej stabilności, zaangażowania w wolne oprogramowanie i szerokiej kompatybilności sprzętowej.',
    tr: 'Ücretsiz ve açık kaynaklı Linux işletim sistemi. Kararlılığı, özgür yazılıma bağlılığı ve geniş donanım uyumluluğu ile tanınır.',
    hv: 'Linux tubis āeksiā gundytyr. Sikagon sytedhy, prisagon naejot āeksiā tubisy, se ampa unduragon.'
  },
  'Kali': {
    es: 'Distribución Linux especializada en seguridad informática y pruebas de penetración. Incluye numerosas herramientas para auditorías de seguridad y análisis forense.',
    en: 'Linux distribution specialized in cybersecurity and penetration testing. Includes numerous tools for security auditing and forensic analysis.',
    'en-us': 'Linux distribution specialized in cybersecurity and penetration testing. Includes numerous tools for security auditing and forensic analysis.',
    'es-mx': 'Distribución Linux especializada en seguridad informática y pruebas de penetración. Incluye numerosas herramientas para auditorías de seguridad y análisis forense.',
    pt: 'Distribuição Linux especializada em cibersegurança e testes de penetração. Inclui numerosas ferramentas para auditoria de segurança e análise forense.',
    fr: 'Distribution Linux spécialisée dans la cybersécurité et les tests d\'intrusion. Comprend de nombreux outils pour l\'audit de sécurité et l\'analyse forensique.',
    de: 'Linux-Distribution, spezialisiert auf Cybersicherheit und Penetrationstests. Enthält zahlreiche Tools für Sicherheitsaudits und forensische Analysen.',
    it: 'Distribuzione Linux specializzata in sicurezza informatica e test di penetrazione. Include numerosi strumenti per l\'auditing di sicurezza e l\'analisi forense.',
    zh: '专注于网络安全和渗透测试的 Linux 发行版。包括用于安全审计和取证分析的众多工具。',
    ja: 'サイバーセキュリティと侵入テストに特化したLinuxディストリビューション。セキュリティ監査とフォレンジック分析のための多数のツールを含みます。',
    ru: 'Дистрибутив Linux, специализирующийся на кибербезопасности и тестировании на проникновение. Включает множество инструментов для аудита безопасности и судебного анализа.',
    ar: 'توزيعة لينكس متخصصة في الأمن السيبراني واختبار الاختراق. تتضمن أدوات عديدة للتدقيق الأمني والتحليل الجنائي.',
    hi: 'साइबर सुरक्षा और पेनेट्रेशन टेस्टिंग में विशेषज्ञता वाला लिनक्स वितरण। सुरक्षा ऑडिटिंग और फोरेंसिक विश्लेषण के लिए कई टूल शामिल हैं।',
    ko: '사이버 보안 및 침투 테스트에 특화된 Linux 배포판. 보안 감사 및 포렌식 분석을 위한 수많은 도구가 포함되어 있습니다.',
    nl: 'Linux-distributie gespecialiseerd in cybersecurity en penetratietesten. Bevat talrijke tools voor beveiligingsaudits en forensische analyse.',
    pl: 'Dystrybucja Linuksa wyspecjalizowana w cyberbezpieczeństwie i testach penetracyjnych. Zawiera liczne narzędzia do audytu bezpieczeństwa i analizy śledczej.',
    tr: 'Siber güvenlik ve sızma testlerinde uzmanlaşmış Linux dağıtımı. Güvenlik denetimi ve adli analiz için çok sayıda araç içerir.',
    hv: 'Linux dubys sytedhy hen sikagon se daomior. Iksā tolma mirri tembyry hen sytedhy se ānogar.'
  },
