// Descripciones para las tecnologías (Parte 2)
// Múltiples idiomas soportados
export const skillDescriptionsPart2 = {
  'Supabase': {
    es: 'Alternativa de código abierto a Firebase. Proporciona base de datos PostgreSQL, autenticación, almacenamiento y funciones en tiempo real.',
    en: 'Open source Firebase alternative. Provides PostgreSQL database, authentication, storage, and real-time functions.',
    'en-us': 'Open source Firebase alternative. Provides PostgreSQL database, authentication, storage, and real-time functions.',
    'es-mx': 'Alternativa de código abierto a Firebase. Proporciona base de datos PostgreSQL, autenticación, almacenamiento y funciones en tiempo real.',
    pt: 'Alternativa de código aberto ao Firebase. Fornece banco de dados PostgreSQL, autenticação, armazenamento e funções em tempo real.',
    fr: 'Alternative open source à Firebase. Fournit une base de données PostgreSQL, une authentification, un stockage et des fonctions en temps réel.',
    de: 'Open Source Firebase-Alternative. Bietet PostgreSQL-Datenbank, Authentifizierung, Speicher und Echtzeit-Funktionen.',
    it: 'Alternativa open source a Firebase. Fornisce database PostgreSQL, autenticazione, archiviazione e funzioni in tempo reale.',
    zh: 'Firebase的开源替代品。提供PostgreSQL数据库、身份验证、存储和实时功能。',
    ja: 'Firebaseのオープンソース代替品。PostgreSQLデータベース、認証、ストレージ、リアルタイム機能を提供します。',
    ru: 'Альтернатива Firebase с открытым исходным кодом. Предоставляет базу данных PostgreSQL, аутентификацию, хранилище и функции реального времени.',
    ar: 'بديل مفتوح المصدر لـ Firebase. يوفر قاعدة بيانات PostgreSQL والمصادقة والتخزين والوظائف في الوقت الفعلي.',
    hi: 'फायरबेस का ओपन सोर्स विकल्प। PostgreSQL डेटाबेस, प्रमाणीकरण, स्टोरेज और रियल-टाइम फंक्शन प्रदान करता है।',
    ko: 'Firebase의 오픈 소스 대안. PostgreSQL 데이터베이스, 인증, 스토리지 및 실시간 기능을 제공합니다.',
    nl: 'Open source Firebase alternatief. Biedt PostgreSQL database, authenticatie, opslag en realtime functies.',
    pl: 'Alternatywa open source dla Firebase. Zapewnia bazę danych PostgreSQL, uwierzytelnianie, pamięć masową i funkcje w czasie rzeczywistym.',
    tr: 'Açık kaynaklı Firebase alternatifi. PostgreSQL veritabanı, kimlik doğrulama, depolama ve gerçek zamanlı işlevler sağlar.',
    hv: 'Firebase tubis. Urnen PostgreSQL tubis, sytedhy, tubys se vēdros sēpa.'
  },
  'MySQL': {
    es: 'Sistema de gestión de bases de datos relacional de código abierto. Ampliamente utilizado para aplicaciones web, rápido y fiable.',
    en: 'Open-source relational database management system. Widely used for web applications, fast and reliable.',
    'en-us': 'Open-source relational database management system. Widely used for web applications, fast and reliable.',
    'es-mx': 'Sistema de gestión de bases de datos relacional de código abierto. Ampliamente utilizado para aplicaciones web, rápido y fiable.',
    pt: 'Sistema de gerenciamento de banco de dados relacional de código aberto. Amplamente utilizado para aplicações web, rápido e confiável.',
    fr: 'Système de gestion de base de données relationnelle open source. Largement utilisé pour les applications web, rapide et fiable.',
    de: 'Open-Source-Relationales Datenbankmanagementsystem. Weit verbreitet für Webanwendungen, schnell und zuverlässig.',
    it: 'Sistema di gestione di database relazionale open source. Ampiamente utilizzato per applicazioni web, veloce e affidabile.',
    zh: '开源关系数据库管理系统。广泛用于Web应用程序，快速且可靠。',
    ja: 'オープンソースのリレーショナルデータベース管理システム。Webアプリケーションに広く使用され、高速で信頼性があります。',
    ru: 'Система управления реляционными базами данных с открытым исходным кодом. Широко используется для веб-приложений, быстрая и надежная.',
    ar: 'نظام إدارة قواعد البيانات العلائقية مفتوح المصدر. يستخدم على نطاق واسع لتطبيقات الويب، سريع وموثوق.',
    hi: 'ओपन-सोर्स रिलेशनल डेटाबेस मैनेजमेंट सिस्टम। वेब एप्लिकेशन के लिए व्यापक रूप से उपयोग किया जाता है, तेज़ और विश्वसनीय।',
    ko: '오픈 소스 관계형 데이터베이스 관리 시스템. 웹 애플리케이션에 널리 사용되며 빠르고 안정적입니다.',
    nl: 'Open-source relationeel databasemanagementsysteem. Veel gebruikt voor webapplicaties, snel en betrouwbaar.',
    pl: 'System zarządzania relacyjnymi bazami danych typu open source. Szeroko stosowany w aplikacjach internetowych, szybki i niezawodny.',
    tr: 'Açık kaynaklı ilişkisel veritabanı yönetim sistemi. Web uygulamaları için yaygın olarak kullanılır, hızlı ve güvenilirdir.',
    hv: 'Ryktys tubis hen uēpa. Bē udra hen gaomagon tubys, lanta se syndrōñe.'
  },
  'Stripe': {
    es: 'Plataforma de procesamiento de pagos en línea. Ofrece APIs para integrar pagos en aplicaciones web y móviles con seguridad y facilidad.',
    en: 'Online payment processing platform. Offers APIs for securely integrating payments into web and mobile applications.',
    'en-us': 'Online payment processing platform. Offers APIs for securely integrating payments into web and mobile applications.',
    'es-mx': 'Plataforma de procesamiento de pagos en línea. Ofrece APIs para integrar pagos en aplicaciones web y móviles con seguridad y facilidad.',
    pt: 'Plataforma de processamento de pagamentos online. Oferece APIs para integrar pagamentos em aplicações web e móveis com segurança e facilidade.',
    fr: 'Plateforme de traitement des paiements en ligne. Offre des APIs pour intégrer des paiements dans des applications web et mobiles de manière sécurisée et facile.',
    de: 'Online-Zahlungsabwicklungsplattform. Bietet APIs zur sicheren und einfachen Integration von Zahlungen in Web- und Mobile-Anwendungen.',
    it: 'Piattaforma di elaborazione dei pagamenti online. Offre API per integrare i pagamenti in applicazioni web e mobili in modo sicuro e facile.',
    zh: '在线支付处理平台。提供API，用于安全地将支付集成到Web和移动应用程序中。',
    ja: 'オンライン決済処理プラットフォーム。Webおよびモバイルアプリケーションにセキュアに決済を統合するためのAPIを提供します。',
    ru: 'Платформа для обработки онлайн-платежей. Предлагает API для безопасной интеграции платежей в веб- и мобильные приложения.',
    ar: 'منصة معالجة المدفوعات عبر الإنترنت. تقدم واجهات برمجة التطبيقات لدمج المدفوعات بشكل آمن في تطبيقات الويب والهاتف المحمول.',
    hi: 'ऑनलाइन भुगतान प्रोसेसिंग प्लेटफॉर्म। वेब और मोबाइल एप्लिकेशन में भुगतान को सुरक्षित रूप से एकीकृत करने के लिए API प्रदान करता है।',
    ko: '온라인 결제 처리 플랫폼. 웹 및 모바일 애플리케이션에 안전하게 결제를 통합하기 위한 API를 제공합니다.',
    nl: 'Online betalingsverwerkingsplatform. Biedt API\'s voor het veilig integreren van betalingen in web- en mobiele applicaties.',
    pl: 'Platforma przetwarzania płatności online. Oferuje API do bezpiecznego integrowania płatności w aplikacjach internetowych i mobilnych.',
    tr: 'Çevrimiçi ödeme işleme platformu. Web ve mobil uygulamalara ödeme sistemlerini güvenli bir şekilde entegre etmek için API\'ler sunar.',
    hv: 'Tubir vōljes hen uēpa. Urnen APIs hen sytedhy vōljes naejot gaomagon tubys.'
  },
  'GraphQL': {
    es: 'Lenguaje de consulta y manipulación de datos para APIs. Permite a los clientes solicitar exactamente los datos que necesitan, reduciendo el exceso de información.',
    en: 'Query and manipulation language for APIs. Allows clients to request exactly the data they need, reducing over-fetching.',
    'en-us': 'Query and manipulation language for APIs. Allows clients to request exactly the data they need, reducing over-fetching.',
    'es-mx': 'Lenguaje de consulta y manipulación de datos para APIs. Permite a los clientes solicitar exactamente los datos que necesitan, reduciendo el exceso de información.',
    pt: 'Linguagem de consulta e manipulação para APIs. Permite que os clientes solicitem exatamente os dados de que precisam, reduzindo o excesso de informações.',
    fr: 'Langage de requête et de manipulation pour les APIs. Permet aux clients de demander exactement les données dont ils ont besoin, réduisant la sur-récupération.',
    de: 'Abfrage- und Manipulationssprache für APIs. Ermöglicht es Clients, genau die Daten anzufordern, die sie benötigen, und reduziert so das Überholen.',
    it: 'Linguaggio di query e manipolazione per API. Consente ai client di richiedere esattamente i dati di cui hanno bisogno, riducendo l\'eccesso di recupero.',
    zh: '用于API的查询和操作语言。允许客户端请求他们确切需要的数据，减少过度获取。',
    ja: 'APIのためのクエリと操作言語。クライアントが必要なデータを正確にリクエストすることを可能にし、オーバーフェッチングを減らします。',
    ru: 'Язык запросов и манипуляций для API. Позволяет клиентам запрашивать именно те данные, которые им нужны, уменьшая избыточную выборку.',
    ar: 'لغة استعلام ومعالجة للواجهات البرمجية. تسمح للعملاء بطلب البيانات التي يحتاجونها بالضبط، مما يقلل من الإفراط في الجلب.',
    hi: 'API के लिए क्वेरी और मैनिप्युलेशन लैंग्वेज। क्लाइंट्स को बिल्कुल वही डेटा अनुरोध करने की अनुमति देता है जिसकी उन्हें आवश्यकता है, जिससे ओवर-फेचिंग कम होती है।',
    ko: 'API를 위한 쿼리 및 조작 언어. 클라이언트가 정확히 필요한 데이터만 요청할 수 있게 해 과도한 데이터 가져오기를 줄입니다.',
    nl: 'Query- en manipulatietaal voor API\'s. Stelt clients in staat om precies de gegevens op te vragen die ze nodig hebben, waardoor overfetching wordt verminderd.',
    pl: 'Język zapytań i manipulacji dla API. Umożliwia klientom żądanie dokładnie tych danych, których potrzebują, zmniejszając nadmierne pobieranie.',
    tr: 'API\'lar için sorgu ve manipülasyon dili. İstemcilerin tam olarak ihtiyaç duydukları verileri istemelerine olanak tanır, aşırı getirmeyi azaltır.',
    hv: 'Valyre hen API tubys. Sikagon uēpa naejot vōljes tubys.'
  },
  'Bun': {
    es: 'Entorno de ejecución JavaScript todo en uno. Incluye gestor de paquetes, bundler y ejecutor de pruebas, diseñado para máxima velocidad.',
    en: 'All-in-one JavaScript runtime. Includes package manager, bundler, and test runner, designed for maximum speed.',
    'en-us': 'All-in-one JavaScript runtime. Includes package manager, bundler, and test runner, designed for maximum speed.',
    'es-mx': 'Entorno de ejecución JavaScript todo en uno. Incluye gestor de paquetes, bundler y ejecutor de pruebas, diseñado para máxima velocidad.',
    pt: 'Runtime JavaScript tudo-em-um. Inclui gerenciador de pacotes, bundler e executor de testes, projetado para velocidade máxima.',
    fr: 'Runtime JavaScript tout-en-un. Comprend un gestionnaire de paquets, un bundler et un exécuteur de tests, conçu pour une vitesse maximale.',
    de: 'All-in-One-JavaScript-Laufzeitumgebung. Enthält Paketmanager, Bundler und Testläufer, entwickelt für maximale Geschwindigkeit.',
    it: 'Runtime JavaScript all-in-one. Include gestore di pacchetti, bundler e runner di test, progettato per la massima velocità.',
    zh: '一体化JavaScript运行时。包括包管理器、打包工具和测试运行器，设计用于最大速度。',
    ja: 'オールインワンのJavaScriptランタイム。パッケージマネージャー、バンドラー、テストランナーを含み、最大速度のために設計されています。',
    ru: 'Универсальная среда выполнения JavaScript. Включает менеджер пакетов, бандлер и средство запуска тестов, разработанные для максимальной скорости.',
    ar: 'بيئة تشغيل JavaScript متكاملة. تشمل مدير الحزم ومجمع ومشغل اختبار، مصممة لأقصى سرعة.',
    hi: 'ऑल-इन-वन जावास्क्रिप्ट रनटाइम। पैकेज मैनेजर, बंडलर और टेस्ट रनर शामिल हैं, अधिकतम गति के लिए डिज़ाइन किया गया है।',
    ko: '올인원 JavaScript 런타임. 패키지 관리자, 번들러 및 테스트 러너를 포함하며 최대 속도를 위해 설계되었습니다.',
    nl: 'Alles-in-één JavaScript runtime. Bevat pakketbeheerder, bundler en testrunner, ontworpen voor maximale snelheid.',
    pl: 'Środowisko uruchomieniowe JavaScript typu all-in-one. Zawiera menedżera pakietów, bundler i narzędzie do uruchamiania testów, zaprojektowane dla maksymalnej szybkości.',
    tr: 'Hepsi bir arada JavaScript çalışma zamanı. Maksimum hız için tasarlanmış paket yöneticisi, paketleyici ve test çalıştırıcısı içerir.',
    hv: 'JavaScript tubir. Tubys ryktys, urnen lanta pōnta.'
  }
};
