// Descripciones para las tecnologías (Parte 4)
// Múltiples idiomas soportados
export const skillDescriptionsPart4 = {
  'Strapi': {
    es: 'CMS headless de código abierto. Permite crear, gestionar y exponer contenido a través de APIs personalizadas con una interfaz amigable.',
    en: 'Open-source headless CMS. Allows creating, managing, and exposing content via custom APIs with a user-friendly interface.',
    'en-us': 'Open-source headless CMS. Allows creating, managing, and exposing content via custom APIs with a user-friendly interface.',
    'es-mx': 'CMS headless de código abierto. Permite crear, gestionar y exponer contenido a través de APIs personalizadas con una interfaz amigable.',
    pt: 'CMS headless de código aberto. Permite criar, gerenciar e expor conteúdo por meio de APIs personalizadas com uma interface amigável.',
    fr: 'CMS headless open source. Permet de créer, gérer et exposer du contenu via des API personnalisées avec une interface conviviale.',
    de: 'Open-Source-Headless-CMS. Ermöglicht das Erstellen, Verwalten und Bereitstellen von Inhalten über benutzerdefinierte APIs mit einer benutzerfreundlichen Oberfläche.',
    it: 'CMS headless open source. Consente di creare, gestire ed esporre contenuti tramite API personalizzate con un\'interfaccia user-friendly.',
    zh: '开源headless CMS。允许通过自定义API创建、管理和公开内容，具有用户友好的界面。',
    ja: 'オープンソースのヘッドレスCMS。ユーザーフレンドリーなインターフェースでカスタムAPIを通じてコンテンツの作成、管理、公開が可能。',
    ru: 'CMS с открытым исходным кодом без фронтенда. Позволяет создавать, управлять и предоставлять контент через пользовательские API с удобным интерфейсом.',
    ar: 'نظام إدارة محتوى بدون واجهة مفتوح المصدر. يسمح بإنشاء وإدارة وعرض المحتوى عبر واجهات برمجة تطبيقات مخصصة مع واجهة سهلة الاستخدام.',
    hi: 'ओपन-सोर्स हेडलेस CMS। यूजर-फ्रेंडली इंटरफेस के साथ कस्टम API के माध्यम से कंटेंट बनाने, मैनेज करने और एक्सपोज करने की अनुमति देता है।',
    ko: '오픈 소스 헤드리스 CMS. 사용자 친화적인 인터페이스로 사용자 지정 API를 통해 콘텐츠를 생성, 관리 및 노출할 수 있습니다.',
    nl: 'Open-source headless CMS. Maakt het mogelijk om inhoud te creëren, beheren en bloot te leggen via aangepaste API\'s met een gebruiksvriendelijke interface.',
    pl: 'CMS typu headless o otwartym kodzie źródłowym. Umożliwia tworzenie, zarządzanie i udostępnianie treści za pośrednictwem niestandardowych API z przyjaznym dla użytkownika interfejsem.',
    tr: 'Açık kaynaklı başsız CMS. Kullanıcı dostu bir arayüzle özel API\'ler aracılığıyla içerik oluşturma, yönetme ve sunma olanağı sağlar.',
    hv: 'CMS tubis. Sikagon vestragon, udra se vēdros tubis naejot API.'
  },
  'Debian': {
    es: 'Sistema operativo basado en Linux de código abierto. Conocido por su estabilidad, seguridad y amplio soporte de software.',
    en: 'Open-source Linux-based operating system. Known for its stability, security, and extensive software support.',
    'en-us': 'Open-source Linux-based operating system. Known for its stability, security, and extensive software support.',
    'es-mx': 'Sistema operativo basado en Linux de código abierto. Conocido por su estabilidad, seguridad y amplio soporte de software.',
    pt: 'Sistema operacional de código aberto baseado em Linux. Conhecido por sua estabilidade, segurança e amplo suporte de software.',
    fr: 'Système d\'exploitation open source basé sur Linux. Connu pour sa stabilité, sa sécurité et son support logiciel étendu.',
    de: 'Open-Source-Linux-basiertes Betriebssystem. Bekannt für seine Stabilität, Sicherheit und umfangreiche Softwareunterstützung.',
    it: 'Sistema operativo open source basato su Linux. Noto per la sua stabilità, sicurezza e ampio supporto software.',
    zh: '基于Linux的开源操作系统。以其稳定性、安全性和广泛的软件支持而闻名。',
    ja: 'Linuxベースのオープンソースオペレーティングシステム。その安定性、セキュリティ、および広範なソフトウェアサポートで知られています。',
    ru: 'Операционная система с открытым исходным кодом на базе Linux. Известна своей стабильностью, безопасностью и обширной поддержкой программного обеспечения.',
    ar: 'نظام تشغيل مفتوح المصدر مبني على Linux. معروف باستقراره وأمانه ودعمه الواسع للبرمجيات.',
    hi: 'ओपन-सोर्स लिनक्स-आधारित ऑपरेटिंग सिस्टम। अपनी स्थिरता, सुरक्षा और व्यापक सॉफ्टवेयर सपोर्ट के लिए जाना जाता है।',
    ko: '오픈 소스 Linux 기반 운영 체제. 안정성, 보안 및 광범위한 소프트웨어 지원으로 알려져 있습니다.',
    nl: 'Open-source Linux-gebaseerd besturingssysteem. Bekend om zijn stabiliteit, veiligheid en uitgebreide softwareondersteuning.',
    pl: 'System operacyjny typu open source oparty na Linuksie. Znany ze stabilności, bezpieczeństwa i szerokiego wsparcia dla oprogramowania.',
    tr: 'Açık kaynaklı Linux tabanlı işletim sistemi. Kararlılığı, güvenliği ve kapsamlı yazılım desteğiyle tanınır.',
    hv: 'Linux gundytyr tubis. Ȳghar sytedhy, syndrōño se uēpa sytilībin.'
  },
  'Kali': {
    es: 'Distribución Linux enfocada en seguridad y pruebas de penetración. Incluye numerosas herramientas para auditoría y análisis de seguridad.',
    en: 'Linux distribution focused on security and penetration testing. Includes numerous tools for security auditing and analysis.',
    'en-us': 'Linux distribution focused on security and penetration testing. Includes numerous tools for security auditing and analysis.',
    'es-mx': 'Distribución Linux enfocada en seguridad y pruebas de penetración. Incluye numerosas herramientas para auditoría y análisis de seguridad.',
    pt: 'Distribuição Linux focada em segurança e testes de penetração. Inclui numerosas ferramentas para auditoria e análise de segurança.',
    fr: 'Distribution Linux axée sur la sécurité et les tests de pénétration. Comprend de nombreux outils pour l\'audit et l\'analyse de sécurité.',
    de: 'Linux-Distribution mit Fokus auf Sicherheit und Penetrationstests. Enthält zahlreiche Tools für Sicherheitsaudits und -analysen.',
    it: 'Distribuzione Linux incentrata sulla sicurezza e sui test di penetrazione. Include numerosi strumenti per il controllo e l\'analisi della sicurezza.',
    zh: '专注于安全和渗透测试的Linux发行版。包括用于安全审计和分析的众多工具。',
    ja: 'セキュリティおよびペネトレーションテストに焦点を当てたLinuxディストリビューション。セキュリティ監査および分析のための多数のツールを含みます。',
    ru: 'Дистрибутив Linux, ориентированный на безопасность и тестирование на проникновение. Включает множество инструментов для аудита и анализа безопасности.',
    ar: 'توزيعة Linux تركز على الأمان واختبار الاختراق. تتضمن العديد من الأدوات لتدقيق وتحليل الأمان.',
    hi: 'सुरक्षा और पेनेट्रेशन टेस्टिंग पर केंद्रित लिनक्स वितरण। सुरक्षा ऑडिटिंग और विश्लेषण के लिए कई उपकरण शामिल हैं।',
    ko: '보안 및 침투 테스트에 중점을 둔 Linux 배포판. 보안 감사 및 분석을 위한 다양한 도구가 포함되어 있습니다.',
    nl: 'Linux-distributie gericht op beveiliging en penetratietesten. Bevat talrijke tools voor beveiligingsaudits en -analyse.',
    pl: 'Dystrybucja Linux skoncentrowana na bezpieczeństwie i testach penetracyjnych. Zawiera liczne narzędzia do audytu i analizy bezpieczeństwa.',
    tr: 'Güvenlik ve sızma testlerine odaklanan Linux dağıtımı. Güvenlik denetimi ve analizi için çok sayıda araç içerir.',
    hv: 'Linux sytedhy se tubys. Urnen tolmiot naejot syndrōño pōja.'
  }
};
