// Descripciones para las tecnologías (Parte 1)
// Múltiples idiomas soportados
export const skillDescriptionsPart1 = {
  'Astro': {
    es: 'Framework web que permite crear sitios rápidos con menos JavaScript. Ofrece renderizado en el servidor por defecto e hidratación parcial.',
    en: 'Web framework for building fast sites with less JavaScript. Offers server-side rendering by default and partial hydration.',
    'en-us': 'Web framework for building fast sites with less JavaScript. Offers server-side rendering by default and partial hydration.',
    'es-mx': 'Framework web que permite crear sitios rápidos con menos JavaScript. Ofrece renderizado en el servidor por defecto e hidratación parcial.',
    pt: 'Framework web para construir sites rápidos com menos JavaScript. Oferece renderização do lado do servidor por padrão e hidratação parcial.',
    fr: 'Framework web pour créer des sites rapides avec moins de JavaScript. Offre un rendu côté serveur par défaut et une hydratation partielle.',
    de: 'Web-Framework zum Erstellen schneller Websites mit weniger JavaScript. Bietet serverseitiges Rendering standardmäßig und teilweise Hydratisierung.',
    it: 'Framework web per creare siti veloci con meno JavaScript. Offre rendering lato server di default e idratazione parziale.',
    zh: '用于构建使用更少JavaScript的快速网站的Web框架。默认提供服务器端渲染和部分水合。',
    ja: '少ないJavaScriptで高速なサイトを構築するためのWebフレームワーク。デフォルトでサーバーサイドレンダリングと部分的なハイドレーションを提供。',
    ru: 'Веб-фреймворк для создания быстрых сайтов с меньшим количеством JavaScript. Предлагает рендеринг на стороне сервера по умолчанию и частичную гидратацию.',
    ar: 'إطار عمل للويب لبناء مواقع سريعة بأقل قدر من JavaScript. يقدم عرضًا من جانب الخادم بشكل افتراضي وترطيبًا جزئيًا.',
    hi: 'कम जावास्क्रिप्ट के साथ तेज़ साइट्स बनाने के लिए वेब फ्रेमवर्क। डिफ़ॉल्ट रूप से सर्वर-साइड रेंडरिंग और आंशिक हाइड्रेशन प्रदान करता है।',
    ko: '더 적은 JavaScript로 빠른 사이트를 구축하기 위한 웹 프레임워크. 기본적으로 서버 측 렌더링 및 부분 하이드레이션을 제공합니다.',
    nl: 'Webframework voor het bouwen van snelle sites met minder JavaScript. Biedt server-side rendering standaard en gedeeltelijke hydratie.',
    pl: 'Framework internetowy do tworzenia szybkich witryn z mniejszą ilością JavaScript. Oferuje renderowanie po stronie serwera domyślnie i częściową hydratację.',
    tr: 'Daha az JavaScript ile hızlı siteler oluşturmak için web framework\'ü. Varsayılan olarak sunucu tarafında işleme ve kısmi hidratasyon sunar.',
    hv: 'Zyhossyr hen vestragon lanta tubys. Urnen vēdros vēdrios hen kostōbor se syndrōñoty.'
  },
  'Vite': {
    es: 'Herramienta de compilación moderna y rápida para JavaScript. Ofrece un servidor de desarrollo con recarga en caliente y compilación optimizada.',
    en: 'Modern and fast build tool for JavaScript. Offers a development server with hot module replacement and optimized build.',
    'en-us': 'Modern and fast build tool for JavaScript. Offers a development server with hot module replacement and optimized build.',
    'es-mx': 'Herramienta de compilación moderna y rápida para JavaScript. Ofrece un servidor de desarrollo con recarga en caliente y compilación optimizada.',
    pt: 'Ferramenta de construção moderna e rápida para JavaScript. Oferece um servidor de desenvolvimento com substituição de módulo quente e construção otimizada.',
    fr: 'Outil de construction moderne et rapide pour JavaScript. Offre un serveur de développement avec remplacement de module à chaud et compilation optimisée.',
    de: 'Modernes und schnelles Build-Tool für JavaScript. Bietet einen Entwicklungsserver mit Hot Module Replacement und optimiertem Build.',
    it: 'Strumento di compilazione moderno e veloce per JavaScript. Offre un server di sviluppo con sostituzione a caldo dei moduli e compilazione ottimizzata.',
    zh: '现代且快速的JavaScript构建工具。提供具有热模块替换和优化构建的开发服务器。',
    ja: 'JavaScriptのためのモダンで高速なビルドツール。ホットモジュール置換と最適化されたビルドを備えた開発サーバーを提供。',
    ru: 'Современный и быстрый инструмент сборки для JavaScript. Предлагает сервер разработки с горячей заменой модулей и оптимизированной сборкой.',
    ar: 'أداة بناء حديثة وسريعة لـ JavaScript. توفر خادم تطوير مع استبدال وحدة ساخنة وبناء محسّن.',
    hi: 'जावास्क्रिप्ट के लिए आधुनिक और तेज़ बिल्ड टूल। हॉट मॉड्यूल रिप्लेसमेंट और ऑप्टिमाइज्ड बिल्ड के साथ डेवलपमेंट सर्वर प्रदान करता है।',
    ko: 'JavaScript를 위한 현대적이고 빠른 빌드 도구. 핫 모듈 교체 및 최적화된 빌드가 있는 개발 서버를 제공합니다.',
    nl: 'Modern en snel bouwgereedschap voor JavaScript. Biedt een ontwikkelingsserver met hot module replacement en geoptimaliseerde build.',
    pl: 'Nowoczesne i szybkie narzędzie do budowania dla JavaScript. Oferuje serwer deweloperski z gorącą wymianą modułów i zoptymalizowaną kompilacją.',
    tr: 'JavaScript için modern ve hızlı derleme aracı. Sıcak modül değiştirme ve optimize edilmiş derleme ile bir geliştirme sunucusu sunar.',
    hv: 'Dōron gūroghon hen JavaScript. Urnen keli vōljes se ōdrikobar.'
  },
  'ExpressJS': {
    es: 'Framework web minimalista y flexible para NodeJS. Proporciona un conjunto robusto de características para aplicaciones web y móviles.',
    en: 'Minimal and flexible web framework for NodeJS. Provides a robust set of features for web and mobile applications.',
    'en-us': 'Minimal and flexible web framework for NodeJS. Provides a robust set of features for web and mobile applications.',
    'es-mx': 'Framework web minimalista y flexible para NodeJS. Proporciona un conjunto robusto de características para aplicaciones web y móviles.',
    pt: 'Framework web minimalista e flexível para NodeJS. Fornece um conjunto robusto de recursos para aplicações web e móveis.',
    fr: 'Framework web minimaliste et flexible pour NodeJS. Fournit un ensemble robuste de fonctionnalités pour les applications web et mobiles.',
    de: 'Minimalistisches und flexibles Web-Framework für NodeJS. Bietet eine robuste Reihe von Funktionen für Web- und Mobile-Anwendungen.',
    it: 'Framework web minimalista e flessibile per NodeJS. Fornisce un set robusto di funzionalità per applicazioni web e mobili.',
    zh: '用于NodeJS的简约灵活的Web框架。为Web和移动应用程序提供一组强大的功能。',
    ja: 'NodeJS用のミニマルで柔軟なWebフレームワーク。Webおよびモバイルアプリケーションのための堅牢な機能セットを提供。',
    ru: 'Минималистичный и гибкий веб-фреймворк для NodeJS. Предоставляет надежный набор функций для веб- и мобильных приложений.',
    ar: 'إطار عمل ويب بسيط ومرن لـ NodeJS. يوفر مجموعة قوية من الميزات لتطبيقات الويب والهاتف المحمول.',
    hi: 'NodeJS के लिए न्यूनतम और लचीला वेब फ्रेमवर्क। वेब और मोबाइल एप्लिकेशन के लिए मजबूत सुविधाओं का सेट प्रदान करता है।',
    ko: 'NodeJS를 위한 미니멀하고 유연한 웹 프레임워크. 웹 및 모바일 애플리케이션을 위한 강력한 기능 세트를 제공합니다.',
    nl: 'Minimaal en flexibel webframework voor NodeJS. Biedt een robuuste set functies voor web- en mobiele applicaties.',
    pl: 'Minimalistyczny i elastyczny framework internetowy dla NodeJS. Zapewnia solidny zestaw funkcji dla aplikacji internetowych i mobilnych.',
    tr: 'NodeJS için minimal ve esnek web framework\'ü. Web ve mobil uygulamalar için sağlam bir özellik seti sağlar.',
    hv: 'Zyhossyr hen NodeJS. Urnen tolmiot hen tubys.'
  },
  'Deno': {
    es: 'Entorno de ejecución seguro para JavaScript y TypeScript. Construido en Rust, con seguridad por defecto y sin sistema de paquetes centralizado.',
    en: 'Secure runtime for JavaScript and TypeScript. Built on Rust with security by default and no centralized package system.',
    'en-us': 'Secure runtime for JavaScript and TypeScript. Built on Rust with security by default and no centralized package system.',
    'es-mx': 'Entorno de ejecución seguro para JavaScript y TypeScript. Construido en Rust, con seguridad por defecto y sin sistema de paquetes centralizado.',
    pt: 'Runtime seguro para JavaScript e TypeScript. Construído em Rust com segurança por padrão e sem sistema de pacotes centralizado.',
    fr: 'Environnement d\'exécution sécurisé pour JavaScript et TypeScript. Construit sur Rust avec une sécurité par défaut et sans système de paquets centralisé.',
    de: 'Sichere Laufzeitumgebung für JavaScript und TypeScript. Auf Rust aufgebaut, mit standardmäßiger Sicherheit und ohne zentralisiertes Paketsystem.',
    it: 'Runtime sicuro per JavaScript e TypeScript. Basato su Rust con sicurezza predefinita e nessun sistema di pacchetti centralizzato.',
    zh: 'JavaScript和TypeScript的安全运行时。基于Rust构建，默认安全且没有集中式包系统。',
    ja: 'JavaScriptとTypeScriptのための安全なランタイム。Rustで構築され、デフォルトでセキュリティが確保され、中央集権的なパッケージシステムがありません。',
    ru: 'Безопасная среда выполнения для JavaScript и TypeScript. Построена на Rust с безопасностью по умолчанию и без централизованной системы пакетов.',
    ar: 'بيئة تشغيل آمنة لـ JavaScript و TypeScript. مبنية على Rust مع الأمان افتراضيًا وبدون نظام حزم مركزي.',
    hi: 'जावास्क्रिप्ट और टाइपस्क्रिप्ट के लिए सुरक्षित रनटाइम। Rust पर बनाया गया, डिफ़ॉल्ट रूप से सुरक्षा के साथ और बिना केंद्रीकृत पैकेज सिस्टम के।',
    ko: 'JavaScript 및 TypeScript를 위한 안전한 런타임. 기본적으로 보안 기능이 있고 중앙 집중식 패키지 시스템이 없는 Rust로 구축되었습니다.',
    nl: 'Veilige runtime voor JavaScript en TypeScript. Gebouwd op Rust met standaard beveiliging en geen gecentraliseerd packagesysteem.',
    pl: 'Bezpieczne środowisko uruchomieniowe dla JavaScript i TypeScript. Zbudowane na Rust z domyślnym bezpieczeństwem i bez scentralizowanego systemu pakietów.',
    tr: 'JavaScript ve TypeScript için güvenli çalışma zamanı. Varsayılan olarak güvenlikle ve merkezi olmayan paket sistemiyle Rust üzerine inşa edilmiştir.',
    hv: 'Syndrōñoty tubir hen JavaScript se TypeScript. Vestragon lī Rust sytedhy.'
  },
  'MongoDB': {
    es: 'Base de datos NoSQL orientada a documentos. Almacena datos en documentos flexibles similares a JSON y ofrece escalabilidad horizontal.',
    en: 'NoSQL document-oriented database. Stores data in flexible JSON-like documents and offers horizontal scalability.',
    'en-us': 'NoSQL document-oriented database. Stores data in flexible JSON-like documents and offers horizontal scalability.',
    'es-mx': 'Base de datos NoSQL orientada a documentos. Almacena datos en documentos flexibles similares a JSON y ofrece escalabilidad horizontal.',
    pt: 'Banco de dados NoSQL orientado a documentos. Armazena dados em documentos flexíveis semelhantes a JSON e oferece escalabilidade horizontal.',
    fr: 'Base de données NoSQL orientée document. Stocke les données dans des documents flexibles similaires à JSON et offre une évolutivité horizontale.',
    de: 'Dokumentenorientierte NoSQL-Datenbank. Speichert Daten in flexiblen JSON-ähnlichen Dokumenten und bietet horizontale Skalierbarkeit.',
    it: 'Database NoSQL orientato ai documenti. Memorizza i dati in documenti flessibili simili a JSON e offre scalabilità orizzontale.',
    zh: '面向文档的NoSQL数据库。将数据存储在灵活的类JSON文档中，并提供水平可扩展性。',
    ja: 'ドキュメント指向のNoSQLデータベース。柔軟なJSONライクなドキュメントにデータを保存し、水平スケーラビリティを提供します。',
    ru: 'Документо-ориентированная база данных NoSQL. Хранит данные в гибких JSON-подобных документах и предлагает горизонтальную масштабируемость.',
    ar: 'قاعدة بيانات NoSQL موجهة للمستندات. تخزن البيانات في مستندات مرنة شبيهة بـ JSON وتوفر قابلية التوسع الأفقي.',
    hi: 'दस्तावेज़-उन्मुख NoSQL डेटाबेस। लचीले JSON-जैसे दस्तावेज़ों में डेटा स्टोर करता है और क्षैतिज स्केलेबिलिटी प्रदान करता है।',
    ko: '문서 지향 NoSQL 데이터베이스. 유연한 JSON과 같은 문서에 데이터를 저장하고 수평 확장성을 제공합니다.',
    nl: 'NoSQL documentgeoriënteerde database. Slaat gegevens op in flexibele JSON-achtige documenten en biedt horizontale schaalbaarheid.',
    pl: 'Zorientowana na dokumenty baza danych NoSQL. Przechowuje dane w elastycznych dokumentach podobnych do JSON i oferuje skalowalność poziomą.',
    tr: 'NoSQL belge odaklı veritabanı. Verileri esnek JSON benzeri belgelerde saklar ve yatay ölçeklenebilirlik sunar.',
    hv: 'NoSQL gaomaks tubis. Tubys sikagon hen JSON-tubis se urnen eji.'
  }
};
