// Descripciones para las tecnologías (Parte 3)
// Múltiples idiomas soportados
export const skillDescriptionsPart3 = {
  'NPM': {
    es: 'Gestor de paquetes por defecto para Node.js. Permite instalar, compartir y gestionar dependencias en proyectos JavaScript.',
    en: 'Default package manager for Node.js. Allows installing, sharing, and managing dependencies in JavaScript projects.',
    'en-us': 'Default package manager for Node.js. Allows installing, sharing, and managing dependencies in JavaScript projects.',
    'es-mx': 'Gestor de paquetes por defecto para Node.js. Permite instalar, compartir y gestionar dependencias en proyectos JavaScript.',
    pt: 'Gerenciador de pacotes padrão para Node.js. Permite instalar, compartilhar e gerenciar dependências em projetos JavaScript.',
    fr: 'Gestionnaire de paquets par défaut pour Node.js. Permet d\'installer, de partager et de gérer les dépendances dans les projets JavaScript.',
    de: 'Standard-Paketmanager für Node.js. Ermöglicht die Installation, Freigabe und Verwaltung von Abhängigkeiten in JavaScript-Projekten.',
    it: 'Gestore di pacchetti predefinito per Node.js. Consente di installare, condividere e gestire le dipendenze nei progetti JavaScript.',
    zh: 'Node.js的默认包管理器。允许在JavaScript项目中安装、共享和管理依赖项。',
    ja: 'Node.jsのデフォルトパッケージマネージャー。JavaScriptプロジェクトで依存関係のインストール、共有、管理が可能。',
    ru: 'Менеджер пакетов по умолчанию для Node.js. Позволяет устанавливать, делиться и управлять зависимостями в проектах JavaScript.',
    ar: 'مدير الحزم الافتراضي لـ Node.js. يسمح بتثبيت ومشاركة وإدارة التبعيات في مشاريع JavaScript.',
    hi: 'Node.js के लिए डिफ़ॉल्ट पैकेज मैनेजर। जावास्क्रिप्ट प्रोजेक्ट्स में डिपेंडेंसीज को इंस्टॉल, शेयर और मैनेज करने की अनुमति देता है।',
    ko: 'Node.js의 기본 패키지 관리자. JavaScript 프로젝트에서 종속성을 설치, 공유 및 관리할 수 있습니다.',
    nl: 'Standaard pakketbeheerder voor Node.js. Maakt het mogelijk om afhankelijkheden in JavaScript-projecten te installeren, delen en beheren.',
    pl: 'Domyślny menedżer pakietów dla Node.js. Umożliwia instalowanie, udostępnianie i zarządzanie zależnościami w projektach JavaScript.',
    tr: 'Node.js için varsayılan paket yöneticisi. JavaScript projelerindeki bağımlılıkları kurma, paylaşma ve yönetme olanağı sağlar.',
    hv: 'Ryktys tubys hen Node.js. Sikagon tubys se ryktys uēpa.'
  },
  'PNPM': {
    es: 'Gestor de paquetes rápido y eficiente en el disco. Usa un almacén de contenido para vincular dependencias en lugar de copiarlas, ahorrando espacio.',
    en: 'Fast and disk-efficient package manager. Uses content-addressable storage to link dependencies instead of copying, saving disk space.',
    'en-us': 'Fast and disk-efficient package manager. Uses content-addressable storage to link dependencies instead of copying, saving disk space.',
    'es-mx': 'Gestor de paquetes rápido y eficiente en el disco. Usa un almacén de contenido para vincular dependencias en lugar de copiarlas, ahorrando espacio.',
    pt: 'Gerenciador de pacotes rápido e eficiente em disco. Usa armazenamento endereçável por conteúdo para vincular dependências em vez de copiá-las, economizando espaço em disco.',
    fr: 'Gestionnaire de paquets rapide et économe en espace disque. Utilise un stockage adressable par contenu pour lier les dépendances au lieu de les copier, économisant ainsi de l\'espace disque.',
    de: 'Schneller und platzsparender Paketmanager. Verwendet inhaltsbezogenen Speicher, um Abhängigkeiten zu verknüpfen, anstatt sie zu kopieren, und spart so Festplattenspeicher.',
    it: 'Gestore di pacchetti veloce ed efficiente sul disco. Utilizza l\'archiviazione indirizzabile per contenuto per collegare le dipendenze invece di copiarle, risparmiando spazio su disco.',
    zh: '快速且磁盘高效的包管理器。使用内容可寻址存储来链接依赖项而不是复制，从而节省磁盘空间。',
    ja: '高速かつディスク効率の良いパッケージマネージャー。依存関係をコピーする代わりにコンテンツアドレス可能なストレージを使用してリンクし、ディスク容量を節約します。',
    ru: 'Быстрый и эффективный по использованию диска менеджер пакетов. Использует адресуемое по содержимому хранилище для связывания зависимостей вместо копирования, экономя место на диске.',
    ar: 'مدير حزم سريع وفعال في استخدام القرص. يستخدم التخزين القابل للعنونة بالمحتوى لربط التبعيات بدلاً من نسخها، مما يوفر مساحة القرص.',
    hi: 'तेज़ और डिस्क-कुशल पैकेज मैनेजर। कॉपी करने के बजाय डिपेंडेंसीज को लिंक करने के लिए कंटेंट-एड्रेसेबल स्टोरेज का उपयोग करता है, जिससे डिस्क स्पेस बचता है।',
    ko: '빠르고 디스크 효율적인 패키지 관리자. 복사하는 대신 콘텐츠 주소 지정 가능 스토리지를 사용하여 종속성을 연결하므로 디스크 공간을 절약합니다.',
    nl: 'Snelle en schijfefficiënte pakketbeheerder. Gebruikt op inhoud adresseerbare opslag om afhankelijkheden te koppelen in plaats van te kopiëren, waardoor schijfruimte wordt bespaard.',
    pl: 'Szybki i efektywny dysk menedżer pakietów. Używa magazynu adresowalnego według zawartości do łączenia zależności zamiast ich kopiowania, oszczędzając miejsce na dysku.',
    tr: 'Hızlı ve disk açısından verimli paket yöneticisi. Disk alanından tasarruf etmek için bağımlılıkları kopyalamak yerine bağlamak için içerik adreslenebilir depolama kullanır.',
    hv: 'Lanta se ēbragon hen tubys ryktys. Sikagon tubys gīmigon.'
  },
  'Vercel': {
    es: 'Plataforma para despliegue de aplicaciones frontend. Ofrece serverless functions, despliegue continuo y optimizaciones automáticas para rendimiento.',
    en: 'Frontend deployment platform. Offers serverless functions, continuous deployment, and automatic performance optimizations.',
    'en-us': 'Frontend deployment platform. Offers serverless functions, continuous deployment, and automatic performance optimizations.',
    'es-mx': 'Plataforma para despliegue de aplicaciones frontend. Ofrece serverless functions, despliegue continuo y optimizaciones automáticas para rendimiento.',
    pt: 'Plataforma de implantação frontend. Oferece funções sem servidor, implantação contínua e otimizações automáticas de desempenho.',
    fr: 'Plateforme de déploiement frontend. Offre des fonctions sans serveur, un déploiement continu et des optimisations automatiques des performances.',
    de: 'Frontend-Deployment-Plattform. Bietet serverlose Funktionen, kontinuierliche Bereitstellung und automatische Leistungsoptimierungen.',
    it: 'Piattaforma di deployment frontend. Offre funzioni serverless, deployment continuo e ottimizzazioni automatiche delle prestazioni.',
    zh: '前端部署平台。提供无服务器功能、持续部署和自动性能优化。',
    ja: 'フロントエンドデプロイメントプラットフォーム。サーバーレス関数、継続的なデプロイメント、自動パフォーマンス最適化を提供します。',
    ru: 'Платформа для развертывания фронтенда. Предлагает бессерверные функции, непрерывное развертывание и автоматическую оптимизацию производительности.',
    ar: 'منصة نشر الواجهة الأمامية. تقدم وظائف بدون خادم ونشر مستمر وتحسينات أداء تلقائية.',
    hi: 'फ्रंटएंड डिप्लॉयमेंट प्लेटफॉर्म। सर्वरलेस फंक्शंस, कंटीन्यूअस डिप्लॉयमेंट और ऑटोमैटिक परफॉर्मेंस ऑप्टिमाइजेशन प्रदान करता है।',
    ko: '프론트엔드 배포 플랫폼. 서버리스 기능, 지속적인 배포 및 자동 성능 최적화를 제공합니다.',
    nl: 'Frontend-implementatieplatform. Biedt serverloze functies, continue implementatie en automatische prestatieoptimalisaties.',
    pl: 'Platforma wdrożeniowa frontendu. Oferuje funkcje bezserwerowe, ciągłe wdrażanie i automatyczne optymalizacje wydajności.',
    tr: 'Ön uç dağıtım platformu. Sunucusuz işlevler, sürekli dağıtım ve otomatik performans optimizasyonları sunar.',
    hv: 'Tubir udra sikudeptor. Urnen udra se pōnta.'
  },
  'C++': {
    es: 'Lenguaje de programación de propósito general, de alto rendimiento. Utilizado en sistemas embebidos, videojuegos, aplicaciones de escritorio y más.',
    en: 'High-performance general-purpose programming language. Used in embedded systems, video games, desktop applications, and more.',
    'en-us': 'High-performance general-purpose programming language. Used in embedded systems, video games, desktop applications, and more.',
    'es-mx': 'Lenguaje de programación de propósito general, de alto rendimiento. Utilizado en sistemas embebidos, videojuegos, aplicaciones de escritorio y más.',
    pt: 'Linguagem de programação de uso geral de alto desempenho. Usado em sistemas embarcados, jogos de vídeo, aplicações de desktop e muito mais.',
    fr: 'Langage de programmation généraliste haute performance. Utilisé dans les systèmes embarqués, les jeux vidéo, les applications de bureau et plus encore.',
    de: 'Hochleistungs-Allzweck-Programmiersprache. Wird in eingebetteten Systemen, Videospielen, Desktop-Anwendungen und mehr verwendet.',
    it: 'Linguaggio di programmazione generico ad alte prestazioni. Utilizzato in sistemi embedded, videogiochi, applicazioni desktop e altro.',
    zh: '高性能通用编程语言。用于嵌入式系统、视频游戏、桌面应用程序等。',
    ja: '高性能の汎用プログラミング言語。組み込みシステム、ビデオゲーム、デスクトップアプリケーションなどで使用されています。',
    ru: 'Высокопроизводительный язык программирования общего назначения. Используется в встраиваемых системах, видеоиграх, настольных приложениях и многом другом.',
    ar: 'لغة برمجة عالية الأداء للأغراض العامة. تستخدم في الأنظمة المدمجة وألعاب الفيديو وتطبيقات سطح المكتب والمزيد.',
    hi: 'उच्च प्रदर्शन वाली सामान्य-उद्देश्य प्रोग्रामिंग भाषा। एम्बेडेड सिस्टम, वीडियो गेम्स, डेस्कटॉप एप्लिकेशन और अधिक में उपयोग किया जाता है।',
    ko: '고성능 범용 프로그래밍 언어. 임베디드 시스템, 비디오 게임, 데스크톱 애플리케이션 등에 사용됩니다.',
    nl: 'Hoogwaardige algemene programmeertaal. Gebruikt in embedded systemen, videogames, desktopapplicaties en meer.',
    pl: 'Wysokowydajny język programowania ogólnego przeznaczenia. Używany w systemach wbudowanych, grach wideo, aplikacjach desktopowych i nie tylko.',
    tr: 'Yüksek performanslı genel amaçlı programlama dili. Gömülü sistemlerde, video oyunlarında, masaüstü uygulamalarında ve daha fazlasında kullanılır.',
    hv: 'Valyre pōnta kodāzma. Udra gaomagon, gaomagon se ābrar.'
  },
  'Phaser': {
    es: 'Framework para desarrollo de juegos 2D en HTML5. Incluye física, animaciones, gestión de objetos y soporte para múltiples dispositivos.',
    en: 'HTML5 2D game development framework. Includes physics, animations, object management, and support for multiple devices.',
    'en-us': 'HTML5 2D game development framework. Includes physics, animations, object management, and support for multiple devices.',
    'es-mx': 'Framework para desarrollo de juegos 2D en HTML5. Incluye física, animaciones, gestión de objetos y soporte para múltiples dispositivos.',
    pt: 'Framework de desenvolvimento de jogos 2D em HTML5. Inclui física, animações, gerenciamento de objetos e suporte para múltiplos dispositivos.',
    fr: 'Framework de développement de jeux 2D en HTML5. Comprend la physique, les animations, la gestion d\'objets et la prise en charge de plusieurs appareils.',
    de: 'HTML5 2D-Spielentwicklungs-Framework. Enthält Physik, Animationen, Objektverwaltung und Unterstützung für mehrere Geräte.',
    it: 'Framework per lo sviluppo di giochi 2D in HTML5. Include fisica, animazioni, gestione degli oggetti e supporto per più dispositivi.',
    zh: 'HTML5 2D游戏开发框架。包括物理、动画、对象管理和对多个设备的支持。',
    ja: 'HTML5の2Dゲーム開発フレームワーク。物理、アニメーション、オブジェクト管理、複数のデバイスのサポートを含みます。',
    ru: 'Фреймворк для разработки 2D-игр на HTML5. Включает физику, анимацию, управление объектами и поддержку нескольких устройств.',
    ar: 'إطار عمل لتطوير ألعاب ثنائية الأبعاد بتقنية HTML5. يتضمن الفيزياء والرسوم المتحركة وإدارة الكائنات ودعم الأجهزة المتعددة.',
    hi: 'HTML5 2D गेम डेवलपमेंट फ्रेमवर्क। इसमें फिज़िक्स, एनिमेशन, ऑब्जेक्ट मैनेजमेंट और कई डिवाइसों के लिए सपोर्ट शामिल है।',
    ko: 'HTML5 2D 게임 개발 프레임워크. 물리, 애니메이션, 개체 관리 및 여러 기기에 대한 지원이 포함됩니다.',
    nl: 'HTML5 2D-spelontwikkelingsframework. Bevat fysica, animaties, objectbeheer en ondersteuning voor meerdere apparaten.',
    pl: 'Framework do tworzenia gier 2D w HTML5. Zawiera fizykę, animacje, zarządzanie obiektami i obsługę wielu urządzeń.',
    tr: 'HTML5 2D oyun geliştirme framework\'ü. Fizik, animasyonlar, nesne yönetimi ve birden fazla cihaz için destek içerir.',
    hv: 'HTML5 2D gaomagon zyhossyr. Urnen māzyryn, ābrar se ābrion naejot tubys.'
  }
};
