// Archivo de configuración central para las descripciones de las skills - Parte 2
// Múltiples idiomas soportados

  'JavaScript': {
    es: 'Lenguaje de programación versátil para crear contenido dinámico e interactivo en sitios web. Compatible con todos los navegadores modernos.',
    en: 'Versatile programming language for creating dynamic and interactive content on websites. Compatible with all modern browsers.',
    'en-us': 'Versatile programming language for creating dynamic and interactive content on websites. Compatible with all modern browsers.',
    'es-mx': 'Lenguaje de programación versátil para crear contenido dinámico e interactivo en sitios web. Compatible con todos los navegadores modernos.',
    pt: 'Linguagem de programação versátil para criar conteúdo dinâmico e interativo em sites. Compatível com todos os navegadores modernos.',
    fr: 'Langage de programmation polyvalent pour créer du contenu dynamique et interactif sur les sites web. Compatible avec tous les navigateurs modernes.',
    de: 'Vielseitige Programmiersprache zum Erstellen dynamischer und interaktiver Inhalte auf Websites. Kompatibel mit allen modernen Browsern.',
    it: 'Linguaggio di programmazione versatile per creare contenuti dinamici e interattivi sui siti web. Compatibile con tutti i browser moderni.',
    zh: '用于在网站上创建动态和交互式内容的多功能编程语言。与所有现代浏览器兼容。',
    ja: 'ウェブサイト上で動的でインタラクティブなコンテンツを作成するための多目的プログラミング言語。全ての現代的なブラウザと互換性あり。',
    ru: 'Универсальный язык программирования для создания динамического и интерактивного контента на веб-сайтах. Совместим со всеми современными браузерами.',
    ar: 'لغة برمجة متعددة الاستخدامات لإنشاء محتوى ديناميكي وتفاعلي على المواقع. متوافقة مع جميع المتصفحات الحديثة.',
    hi: 'वेबसाइटों पर गतिशील और इंटरैक्टिव सामग्री बनाने के लिए बहुमुखी प्रोग्रामिंग भाषा। सभी आधुनिक ब्राउज़रों के साथ संगत।',
    ko: '웹사이트에서 동적이고 상호작용하는 콘텐츠를 만들기 위한 다재다능한 프로그래밍 언어. 모든 현대 브라우저와 호환됩니다.',
    nl: 'Veelzijdige programmeertaal voor het creëren van dynamische en interactieve inhoud op websites. Compatibel met alle moderne browsers.',
    pl: 'Wszechstronny język programowania do tworzenia dynamicznych i interaktywnych treści na stronach internetowych. Kompatybilny ze wszystkimi nowoczesnymi przeglądarkami.',
    tr: 'Web sitelerinde dinamik ve etkileşimli içerik oluşturmak için çok yönlü programlama dili. Tüm modern tarayıcılarla uyumludur.',
    hv: 'Rhaenyō kodātyr vestragon sikagion gaomaksir. Syndrōñe lanta mirehī.'
  },
  'TypeScript': {
    es: 'Superset tipado de JavaScript que añade tipos estáticos opcionales. Mejora la calidad del código y la experiencia de desarrollo.',
    en: 'Typed superset of JavaScript that adds optional static types. Improves code quality and development experience.',
    'en-us': 'Typed superset of JavaScript that adds optional static types. Improves code quality and development experience.',
    'es-mx': 'Superset tipado de JavaScript que añade tipos estáticos opcionales. Mejora la calidad del código y la experiencia de desarrollo.',
    pt: 'Superconjunto tipado de JavaScript que adiciona tipos estáticos opcionais. Melhora a qualidade do código e a experiência de desenvolvimento.',
    fr: 'Sur-ensemble typé de JavaScript qui ajoute des types statiques optionnels. Améliore la qualité du code et l\'expérience de développement.',
    de: 'Typisiertes Superset von JavaScript, das optionale statische Typen hinzufügt. Verbessert die Codequalität und die Entwicklungserfahrung.',
    it: 'Superset tipizzato di JavaScript che aggiunge tipi statici opzionali. Migliora la qualità del codice e l\'esperienza di sviluppo.',
    zh: 'JavaScript 的类型化超集，增加了可选的静态类型。提高代码质量和开发体验。',
    ja: 'オプションの静的型を追加するJavaScriptの型付きスーパーセット。コード品質と開発体験を向上。',
    ru: 'Типизированный суперсет JavaScript, добавляющий необязательные статические типы. Улучшает качество кода и опыт разработки.',
    ar: 'مجموعة فائقة من JavaScript تضيف أنواعًا ثابتة اختيارية. يحسن جودة الكود وتجربة التطوير.',
    hi: 'जावास्क्रिप्ट का टाइप्ड सुपरसेट जो वैकल्पिक स्टैटिक टाइप्स जोड़ता है। कोड की गुणवत्ता और विकास अनुभव को बेहतर बनाता है।',
    ko: '선택적 정적 타입을 추가하는 JavaScript의 타입 지정 상위 집합. 코드 품질과 개발 경험을 향상시킵니다.',
    nl: 'Getypeerde superset van JavaScript die optionele statische typen toevoegt. Verbetert codekwaliteit en ontwikkelingservaring.',
    pl: 'Typowany nadzbiór JavaScript, który dodaje opcjonalne typy statyczne. Poprawia jakość kodu i doświadczenie programistyczne.',
    tr: 'JavaScript\'in isteğe bağlı statik tipler ekleyen tipli bir üst kümesi. Kod kalitesini ve geliştirme deneyimini iyileştirir.',
    hv: 'Skorkydor JavaScript se tubis sikagon. Gūrogon kodāty pōntyr sytilībin.'
  },
  'React': {
    es: 'Biblioteca JavaScript para construir interfaces de usuario con componentes reutilizables. Desarrollada por Facebook, permite crear aplicaciones web de una sola página.',
    en: 'JavaScript library for building user interfaces with reusable components. Developed by Facebook, allows creating single-page applications.',
    'en-us': 'JavaScript library for building user interfaces with reusable components. Developed by Facebook, allows creating single-page applications.',
    'es-mx': 'Biblioteca JavaScript para construir interfaces de usuario con componentes reutilizables. Desarrollada por Facebook, permite crear aplicaciones web de una sola página.',
    pt: 'Biblioteca JavaScript para construir interfaces de usuário com componentes reutilizáveis. Desenvolvida pelo Facebook, permite criar aplicações de página única.',
    fr: 'Bibliothèque JavaScript pour construire des interfaces utilisateur avec des composants réutilisables. Développée par Facebook, permet de créer des applications à page unique.',
    de: 'JavaScript-Bibliothek zum Erstellen von Benutzeroberflächen mit wiederverwendbaren Komponenten. Von Facebook entwickelt, ermöglicht die Erstellung von Single-Page-Anwendungen.',
    it: 'Libreria JavaScript per costruire interfacce utente con componenti riutilizzabili. Sviluppata da Facebook, consente di creare applicazioni a pagina singola.',
    zh: '用于构建具有可重用组件的用户界面的JavaScript库。由Facebook开发，允许创建单页应用程序。',
    ja: '再利用可能なコンポーネントでユーザーインターフェースを構築するためのJavaScriptライブラリ。Facebookによって開発され、シングルページアプリケーションの作成が可能。',
    ru: 'Библиотека JavaScript для создания пользовательских интерфейсов с многоразовыми компонентами. Разработана Facebook, позволяет создавать одностраничные приложения.',
    ar: 'مكتبة JavaScript لبناء واجهات المستخدم باستخدام مكونات قابلة لإعادة الاستخدام. طورتها Facebook، وتسمح بإنشاء تطبيقات الصفحة الواحدة.',
    hi: 'पुन: प्रयोज्य कम्पोनेन्ट्स के साथ उपयोगकर्ता इंटरफेस बनाने के लिए जावास्क्रिप्ट लाइब्रेरी। फेसबुक द्वारा विकसित, एकल-पृष्ठ एप्लिकेशन बनाने की अनुमति देता है।',
    ko: '재사용 가능한 컴포넌트로 사용자 인터페이스를 구축하기 위한 JavaScript 라이브러리. Facebook에서 개발했으며 단일 페이지 애플리케이션을 만들 수 있습니다.',
    nl: 'JavaScript-bibliotheek voor het bouwen van gebruikersinterfaces met herbruikbare componenten. Ontwikkeld door Facebook, maakt het mogelijk om single-page applicaties te creëren.',
    pl: 'Biblioteka JavaScript do budowania interfejsów użytkownika z wykorzystaniem komponentów wielokrotnego użytku. Opracowana przez Facebook, umożliwia tworzenie aplikacji jednostronicowych.',
    tr: 'Yeniden kullanılabilir bileşenlerle kullanıcı arayüzleri oluşturmak için JavaScript kütüphanesi. Facebook tarafından geliştirilmiş olup, tek sayfalık uygulamalar oluşturmaya olanak tanır.',
    hv: 'Ubrardy JavaScript hen uhtyghir uēpa iderenigon. Facebook morghor, sikagon gaomagon sikagon.'
  },
  'NextJS': {
    es: 'Framework React para aplicaciones web renderizadas por servidor con generación estática y dinámica. Ofrece enrutamiento, optimización y más características.',
    en: 'React framework for server-rendered web applications with static and dynamic generation. Offers routing, optimization, and more features.',
    'en-us': 'React framework for server-rendered web applications with static and dynamic generation. Offers routing, optimization, and more features.',
    'es-mx': 'Framework React para aplicaciones web renderizadas por servidor con generación estática y dinámica. Ofrece enrutamiento, optimización y más características.',
    pt: 'Framework React para aplicações web renderizadas pelo servidor com geração estática e dinâmica. Oferece roteamento, otimização e mais recursos.',
    fr: 'Framework React pour applications web rendues côté serveur avec génération statique et dynamique. Offre le routage, l\'optimisation et d\'autres fonctionnalités.',
    de: 'React-Framework für serverseitig gerenderte Webanwendungen mit statischer und dynamischer Generierung. Bietet Routing, Optimierung und weitere Funktionen.',
    it: 'Framework React per applicazioni web renderizzate lato server con generazione statica e dinamica. Offre routing, ottimizzazione e altre funzionalità.',
    zh: '用于服务器端渲染的React框架，支持静态和动态生成。提供路由、优化等功能。',
    ja: '静的および動的生成を備えたサーバーレンダリングウェブアプリケーション向けのReactフレームワーク。ルーティング、最適化などの機能を提供。',
    ru: 'React-фреймворк для серверного рендеринга веб-приложений со статической и динамической генерацией. Предлагает маршрутизацию, оптимизацию и другие функции.',
    ar: 'إطار عمل React لتطبيقات الويب المقدمة من الخادم مع التوليد الثابت والديناميكي. يوفر التوجيه والتحسين والمزيد من الميزات.',
    hi: 'स्टैटिक और डायनामिक जेनरेशन के साथ सर्वर-रेंडर्ड वेब एप्लिकेशन के लिए रिएक्ट फ्रेमवर्क। राउटिंग, ऑप्टिमाइजेशन, और अधिक सुविधाएँ प्रदान करता है।',
    ko: '정적 및 동적 생성이 가능한 서버 렌더링 웹 애플리케이션을 위한 React 프레임워크. 라우팅, 최적화 등의 기능을 제공합니다.',
    nl: 'React-framework voor server-gerenderde webapplicaties met statische en dynamische generatie. Biedt routing, optimalisatie en meer functies.',
    pl: 'Framework React do aplikacji internetowych renderowanych po stronie serwera z generowaniem statycznym i dynamicznym. Oferuje routing, optymalizację i więcej funkcji.',
    tr: 'Statik ve dinamik oluşturma ile sunucu tarafında işlenen web uygulamaları için React framework\'ü. Yönlendirme, optimizasyon ve daha fazla özellik sunar.',
    hv: 'Zyhossyr React hen kostōbi gaomagon sikudeptor. Urnen daomior, ñuhomy se tolmiot.'
  },
  'Astro': {
    es: 'Framework web moderno para sitios impulsados por contenido. Combina componentes de múltiples frameworks con un rendimiento óptimo y mínimo JavaScript.',
    en: 'Modern web framework for content-driven websites. Combines components from multiple frameworks with optimal performance and minimal JavaScript.',
    'en-us': 'Modern web framework for content-driven websites. Combines components from multiple frameworks with optimal performance and minimal JavaScript.',
    'es-mx': 'Framework web moderno para sitios impulsados por contenido. Combina componentes de múltiples frameworks con un rendimiento óptimo y mínimo JavaScript.',
    pt: 'Framework web moderno para sites orientados a conteúdo. Combina componentes de vários frameworks com desempenho ideal e JavaScript mínimo.',
    fr: 'Framework web moderne pour sites axés sur le contenu. Combine des composants de plusieurs frameworks avec des performances optimales et un minimum de JavaScript.',
    de: 'Modernes Web-Framework für inhaltsorientierte Websites. Kombiniert Komponenten aus mehreren Frameworks mit optimaler Leistung und minimalem JavaScript.',
    it: 'Framework web moderno per siti web basati su contenuti. Combina componenti di più framework con prestazioni ottimali e JavaScript minimo.',
    zh: '用于内容驱动型网站的现代网络框架。将多个框架的组件结合起来，具有最佳性能和最少的JavaScript。',
    ja: 'コンテンツ駆動型Webサイト向けの最新Webフレームワーク。複数のフレームワークからのコンポーネントを最適なパフォーマンスと最小限のJavaScriptで組み合わせます。',
    ru: 'Современный веб-фреймворк для сайтов, ориентированных на контент. Объединяет компоненты из нескольких фреймворков с оптимальной производительностью и минимальным JavaScript.',
    ar: 'إطار عمل حديث للويب للمواقع التي يحركها المحتوى. يجمع بين مكونات من أطر عمل متعددة مع أداء مثالي وحد أدنى من JavaScript.',
    hi: 'सामग्री-संचालित वेबसाइटों के लिए आधुनिक वेब फ्रेमवर्क। कई फ्रेमवर्क से कंपोनेंट्स को इष्टतम प्रदर्शन और न्यूनतम जावास्क्रिप्ट के साथ जोड़ता है।',
    ko: '콘텐츠 중심 웹사이트를 위한 현대적인 웹 프레임워크. 여러 프레임워크의 구성 요소를 최적의 성능과 최소한의 JavaScript로 결합합니다.',
    nl: 'Modern webframework voor contentgestuurde websites. Combineert componenten van meerdere frameworks met optimale prestaties en minimale JavaScript.',
    pl: 'Nowoczesny framework internetowy dla stron opartych na treści. Łączy komponenty z wielu frameworków z optymalną wydajnością i minimalnym JavaScript.',
    tr: 'İçerik odaklı web siteleri için modern web çerçevesi. Birden fazla çerçeveden bileşenleri optimal performans ve minimum JavaScript ile birleştirir.',
    hv: 'Zyhossyr gaomilaksir sikudeptor hen tubis. Unsyn tubisy gōntan pāsȳt ziōre se JavaScript.'
  },
  'Vite': {
    es: 'Herramienta de compilación frontend moderna que ofrece un desarrollo más rápido. Proporciona un servidor de desarrollo con reemplazo de módulos en caliente y compilación optimizada.',
    en: 'Modern frontend build tool offering faster development. Provides a dev server with hot module replacement and optimized build.',
    'en-us': 'Modern frontend build tool offering faster development. Provides a dev server with hot module replacement and optimized build.',
    'es-mx': 'Herramienta de compilación frontend moderna que ofrece un desarrollo más rápido. Proporciona un servidor de desarrollo con reemplazo de módulos en caliente y compilación optimizada.',
    pt: 'Ferramenta de compilação frontend moderna que oferece desenvolvimento mais rápido. Fornece um servidor de desenvolvimento com substituição de módulo a quente e compilação otimizada.',
    fr: 'Outil de construction frontend moderne offrant un développement plus rapide. Fournit un serveur de développement avec remplacement de module à chaud et compilation optimisée.',
    de: 'Modernes Frontend-Build-Tool für schnellere Entwicklung. Bietet einen Entwicklungsserver mit Hot Module Replacement und optimiertem Build.',
    it: 'Moderno strumento di build frontend che offre uno sviluppo più veloce. Fornisce un server di sviluppo con sostituzione del modulo a caldo e build ottimizzata.',
    zh: '现代前端构建工具，提供更快的开发。提供具有热模块替换和优化构建的开发服务器。',
    ja: '高速な開発を提供する最新のフロントエンド構築ツール。ホットモジュール置換と最適化されたビルドを備えた開発サーバーを提供します。',
    ru: 'Современный инструмент сборки фронтенда, обеспечивающий более быструю разработку. Предоставляет сервер разработки с горячей заменой модулей и оптимизированной сборкой.',
    ar: 'أداة بناء واجهة أمامية حديثة توفر تطويرًا أسرع. توفر خادم تطوير مع استبدال الوحدة النمطية الساخنة وبناء محسّن.',
    hi: 'आधुनिक फ्रंटएंड बिल्ड टूल जो तेज़ विकास प्रदान करता है। हॉट मॉड्यूल रिप्लेसमेंट और अनुकूलित बिल्ड के साथ एक डेव सर्वर प्रदान करता है।',
    ko: '더 빠른 개발을 제공하는 현대적인 프론트엔드 빌드 도구. 핫 모듈 교체 및 최적화된 빌드가 포함된 개발 서버를 제공합니다.',
    nl: 'Moderne frontend-buildtool die snellere ontwikkeling biedt. Biedt een ontwikkelingsserver met hot module replacement en geoptimaliseerde build.',
    pl: 'Nowoczesne narzędzie do budowania frontendu oferujące szybszy rozwój. Zapewnia serwer deweloperski z gorącą wymianą modułów i zoptymalizowaną kompilacją.',
    tr: 'Daha hızlı geliştirme sunan modern frontend yapı aracı. Sıcak modül değiştirme ve optimize edilmiş derleme ile bir geliştirme sunucusu sağlar.',
    hv: 'Qrinuntys tembyr veragon mazōrety vestragon. Urnen tubisy pōnta paktot mazilībagon.'
  },
