// Archivo de configuración para las descripciones de habilidades de backend y bases de datos
// Múltiples idiomas soportados

type SkillDescription = {
  [lang: string]: string;
};

type SkillDescriptions = {
  [skill: string]: SkillDescription;
};

export const backendDatabaseSkillDescriptions: SkillDescriptions = {
  // Backend
  'NodeJS': {
    es: 'Entorno de ejecución de JavaScript de alto rendimiento para desarrollo de aplicaciones del lado del servidor. Experiencia avanzada en arquitecturas escalables y microservicios.',
    en: 'High-performance JavaScript runtime for server-side application development. Advanced experience in scalable architectures and microservices.',
    'en-us': 'High-performance JavaScript runtime for server-side application development. Advanced experience in scalable architectures and microservices.',
    'es-mx': 'Entorno de ejecución de JavaScript de alto rendimiento para desarrollo de aplicaciones del lado del servidor. Experiencia avanzada en arquitecturas escalables y microservicios.',
    pt: 'Ambiente de execução JavaScript de alto desempenho para desenvolvimento de aplicações do lado do servidor. Experiência avançada em arquiteturas escaláveis e microsserviços.',
    fr: 'Environnement d\'exécution JavaScript haute performance pour le développement d\'applications côté serveur. Expérience avancée en architectures évolutives et microservices.',
    de: 'Hochleistungs-JavaScript-Laufzeitumgebung für die serverseitige Anwendungsentwicklung. Fortgeschrittene Erfahrung in skalierbaren Architekturen und Microservices.',
    it: 'Runtime JavaScript ad alte prestazioni per lo sviluppo di applicazioni lato server. Esperienza avanzata in architetture scalabili e microservizi.',
    zh: '用于服务器端应用程序开发的高性能JavaScript运行时。在可扩展架构和微服务方面拥有高级经验。',
    ja: 'サーバーサイドアプリケーション開発のための高性能JavaScriptランタイム。スケーラブルアーキテクチャやマイクロサービスの高度な経験。',
    ru: 'Высокопроизводительная среда выполнения JavaScript для разработки серверных приложений. Продвинутый опыт в масштабируемых архитектурах и микросервисах.',
    ar: 'بيئة تشغيل JavaScript عالية الأداء لتطوير التطبيقات من جانب الخادم. خبرة متقدمة في الهندسة المعمارية القابلة للتوسع والخدمات المصغرة.',
    hi: 'सर्वर-साइड एप्लिकेशन डेवलपमेंट के लिए उच्च-प्रदर्शन जावास्क्रिप्ट रनटाइम। स्केलेबल आर्किटेक्चर और माइक्रोसर्विसेज में उन्नत अनुभव।',
    ko: '서버 측 애플리케이션 개발을 위한 고성능 JavaScript 런타임. 확장 가능한 아키텍처 및 마이크로서비스에서의 고급 경험.',
    nl: 'Hoogwaardige JavaScript-runtime voor server-side applicatieontwikkeling. Geavanceerde ervaring in schaalbare architecturen en microservices.',
    pl: 'Wysokowydajne środowisko uruchomieniowe JavaScript do tworzenia aplikacji po stronie serwera. Zaawansowane doświadczenie w skalowalnych architekturach i mikroserwisach.',
    tr: 'Sunucu tarafı uygulama geliştirmek için yüksek performanslı JavaScript çalışma zamanı. Ölçeklenebilir mimariler ve mikroservisler konusunda ileri düzey deneyim.',
    hv: 'JavaScript tubir tembyr glaeson hen hūchtys. Naejot sȳndror ropagon se sytilīby udlissy.'
  },
  'ExpressJS': {
    es: 'Framework minimalista para Node.js que facilita la creación de aplicaciones web y APIs. Ideal para construir servicios backend robustos y eficientes.',
    en: 'Minimalist framework for Node.js that simplifies web application and API development. Ideal for building robust and efficient backend services.',
    'en-us': 'Minimalist framework for Node.js that simplifies web application and API development. Ideal for building robust and efficient backend services.',
    'es-mx': 'Framework minimalista para Node.js que facilita la creación de aplicaciones web y APIs. Ideal para construir servicios backend robustos y eficientes.',
    pt: 'Framework minimalista para Node.js que simplifica o desenvolvimento de aplicações web e APIs. Ideal para construir serviços de backend robustos e eficientes.',
    fr: 'Framework minimaliste pour Node.js qui simplifie le développement d\'applications web et d\'API. Idéal pour construire des services backend robustes et efficaces.',
    de: 'Minimalistisches Framework für Node.js, das die Entwicklung von Webanwendungen und APIs vereinfacht. Ideal für den Aufbau robuster und effizienter Backend-Dienste.',
    it: 'Framework minimalista per Node.js che semplifica lo sviluppo di applicazioni web e API. Ideale per costruire servizi backend robusti ed efficienti.',
    zh: '用于Node.js的极简框架，简化了Web应用程序和API开发。非常适合构建健壮高效的后端服务。',
    ja: 'Node.js向けのミニマリストフレームワーク。WebアプリケーションとAPI開発を簡素化します。堅牢で効率的なバックエンドサービスの構築に最適。',
    ru: 'Минималистичный фреймворк для Node.js, упрощающий разработку веб-приложений и API. Идеально подходит для создания надежных и эффективных серверных служб.',
    ar: 'إطار عمل بسيط لـ Node.js يبسط تطوير تطبيقات الويب وواجهات برمجة التطبيقات. مثالي لبناء خدمات الواجهة الخلفية القوية والفعالة.',
    hi: 'Node.js के लिए मिनिमलिस्ट फ्रेमवर्क जो वेब एप्लिकेशन और API डेवलपमेंट को सरल बनाता है। मजबूत और कुशल बैकएंड सेवाओं के निर्माण के लिए आदर्श।',
    ko: 'Node.js를 위한 미니멀리스트 프레임워크로 웹 애플리케이션 및 API 개발을 단순화합니다. 견고하고 효율적인 백엔드 서비스 구축에 이상적입니다.',
    nl: 'Minimalistische framework voor Node.js dat web-applicatie- en API-ontwikkeling vereenvoudigt. Ideaal voor het bouwen van robuuste en efficiënte backend-services.',
    pl: 'Minimalistyczny framework dla Node.js, który upraszcza tworzenie aplikacji internetowych i API. Idealny do budowania solidnych i wydajnych usług backendowych.',
    tr: 'Web uygulaması ve API geliştirmeyi basitleştiren Node.js için minimalist framework. Sağlam ve verimli backend hizmetleri oluşturmak için idealdir.',
    hv: 'Zyhossyr tubos hen Node.js se māzigon gaomagon sikudeptor. Naejot gaomagon sȳndror se tembyr.'
  },
  'Deno': {
    es: 'Runtime JavaScript y TypeScript seguro con permisos explícitos y sin npm. Creado por el fundador de Node.js como alternativa moderna y segura.',
    en: 'Secure JavaScript and TypeScript runtime with explicit permissions and no npm. Created by the founder of Node.js as a modern and secure alternative.',
    'en-us': 'Secure JavaScript and TypeScript runtime with explicit permissions and no npm. Created by the founder of Node.js as a modern and secure alternative.',
    'es-mx': 'Runtime JavaScript y TypeScript seguro con permisos explícitos y sin npm. Creado por el fundador de Node.js como alternativa moderna y segura.',
    pt: 'Runtime JavaScript e TypeScript seguro com permissões explícitas e sem npm. Criado pelo fundador do Node.js como uma alternativa moderna e segura.',
    fr: 'Runtime JavaScript et TypeScript sécurisé avec des permissions explicites et sans npm. Créé par le fondateur de Node.js comme une alternative moderne et sécurisée.',
    de: 'Sichere JavaScript- und TypeScript-Laufzeitumgebung mit expliziten Berechtigungen und ohne npm. Vom Gründer von Node.js als moderne und sichere Alternative geschaffen.',
    it: 'Runtime JavaScript e TypeScript sicuro con autorizzazioni esplicite e senza npm. Creato dal fondatore di Node.js come alternativa moderna e sicura.',
    zh: '具有明确权限且不使用npm的安全JavaScript和TypeScript运行时。由Node.js的创始人创建，作为现代安全的替代方案。',
    ja: '明示的な権限を持ち、npmを使用しない安全なJavaScriptとTypeScriptのランタイム。Node.jsの創設者によって、現代的で安全な代替品として作成されました。',
    ru: 'Безопасная среда выполнения JavaScript и TypeScript с явными разрешениями и без npm. Создана основателем Node.js как современная и безопасная альтернатива.',
    ar: 'بيئة تشغيل JavaScript و TypeScript آمنة مع أذونات صريحة وبدون npm. تم إنشاؤه بواسطة مؤسس Node.js كبديل حديث وآمن.',
    hi: 'स्पष्ट अनुमतियों और बिना npm के सुरक्षित जावास्क्रिप्ट और टाइपस्क्रिप्ट रनटाइम। Node.js के संस्थापक द्वारा एक आधुनिक और सुरक्षित विकल्प के रूप में बनाया गया।',
    ko: '명시적 권한이 있고 npm이 없는 안전한 JavaScript 및 TypeScript 런타임. Node.js의 창시자가 현대적이고 안전한 대안으로 만들었습니다.',
    nl: 'Veilige JavaScript- en TypeScript-runtime met expliciete toestemmingen en zonder npm. Gemaakt door de oprichter van Node.js als een modern en veilig alternatief.',
    pl: 'Bezpieczne środowisko uruchomieniowe JavaScript i TypeScript z jawnymi uprawnieniami i bez npm. Stworzone przez założyciela Node.js jako nowoczesna i bezpieczna alternatywa.',
    tr: 'Açık izinlerle ve npm olmadan güvenli JavaScript ve TypeScript çalışma zamanı. Node.js\'in kurucusu tarafından modern ve güvenli bir alternatif olarak yaratılmıştır.',
    hv: 'JavaScript se TypeScript tubir sȳndrior uēpa isse daoriot. Node.js morghor tembyr se sȳndror.'
  },
  'Bun': {
    es: 'Runtime JavaScript todo en uno extremadamente rápido con gestor de paquetes integrado y framework para servidores. Optimizado para rendimiento y desarrolladores TypeScript.',
    en: 'All-in-one extremely fast JavaScript runtime with built-in package manager and server framework. Optimized for performance and TypeScript developers.',
    'en-us': 'All-in-one extremely fast JavaScript runtime with built-in package manager and server framework. Optimized for performance and TypeScript developers.',
    'es-mx': 'Runtime JavaScript todo en uno extremadamente rápido con gestor de paquetes integrado y framework para servidores. Optimizado para rendimiento y desarrolladores TypeScript.',
    pt: 'Runtime JavaScript tudo-em-um extremamente rápido com gerenciador de pacotes integrado e framework para servidores. Otimizado para desempenho e desenvolvedores TypeScript.',
    fr: 'Runtime JavaScript tout-en-un extrêmement rapide avec gestionnaire de paquets intégré et framework serveur. Optimisé pour les performances et les développeurs TypeScript.',
    de: 'Extrem schnelle All-in-One-JavaScript-Laufzeitumgebung mit integriertem Paketmanager und Server-Framework. Optimiert für Leistung und TypeScript-Entwickler.',
    it: 'Runtime JavaScript all-in-one estremamente veloce con gestore di pacchetti integrato e framework per server. Ottimizzato per le prestazioni e gli sviluppatori TypeScript.',
    zh: '具有内置包管理器和服务器框架的极其快速的一体化JavaScript运行时。针对性能和TypeScript开发人员进行了优化。',
    ja: '内蔵パッケージマネージャーとサーバーフレームワークを備えた、非常に高速なオールインワンJavaScriptランタイム。パフォーマンスとTypeScript開発者向けに最適化。',
    ru: 'Чрезвычайно быстрая универсальная среда выполнения JavaScript со встроенным менеджером пакетов и серверным фреймворком. Оптимизирована для производительности и разработчиков TypeScript.',
    ar: 'بيئة تشغيل JavaScript سريعة للغاية متكاملة مع مدير حزم مضمن وإطار عمل للخوادم. مُحسّن للأداء ومطوري TypeScript.',
    hi: 'बिल्ट-इन पैकेज मैनेजर और सर्वर फ्रेमवर्क के साथ अत्यधिक तेज़ ऑल-इन-वन जावास्क्रिप्ट रनटाइम। प्रदर्शन और टाइपस्क्रिप्ट डेवलपर्स के लिए अनुकूलित।',
    ko: '내장된 패키지 관리자 및 서버 프레임워크가 있는 매우 빠른 올인원 JavaScript 런타임. 성능 및 TypeScript 개발자를 위해 최적화되었습니다.',
    nl: 'Extreem snelle alles-in-één JavaScript-runtime met ingebouwde pakketbeheerder en serverframework. Geoptimaliseerd voor prestaties en TypeScript-ontwikkelaars.',
    pl: 'Niezwykle szybkie środowisko uruchomieniowe JavaScript typu all-in-one z wbudowanym menedżerem pakietów i frameworkiem serwerowym. Zoptymalizowane pod kątem wydajności i programistów TypeScript.',
    tr: 'Yerleşik paket yöneticisi ve sunucu framework\'ü ile son derece hızlı, hepsi bir arada JavaScript çalışma zamanı. Performans ve TypeScript geliştiricileri için optimize edilmiştir.',
    hv: 'JavaScript tubir tembyr tembyr daomion isse vēttir. Ropagon tembyr se TypeScript vestriarzir.'
  },
  
  // Bases de datos
  'MongoDB': {
    es: 'Base de datos NoSQL orientada a documentos, escalable y de alto rendimiento. Perfecta para aplicaciones modernas con datos no estructurados y esquemas flexibles.',
    en: 'Document-oriented, scalable, high-performance NoSQL database. Perfect for modern applications with unstructured data and flexible schemas.',
    'en-us': 'Document-oriented, scalable, high-performance NoSQL database. Perfect for modern applications with unstructured data and flexible schemas.',
    'es-mx': 'Base de datos NoSQL orientada a documentos, escalable y de alto rendimiento. Perfecta para aplicaciones modernas con datos no estructurados y esquemas flexibles.',
    pt: 'Banco de dados NoSQL orientado a documentos, escalável e de alto desempenho. Perfeito para aplicações modernas com dados não estruturados e esquemas flexíveis.',
    fr: 'Base de données NoSQL orientée document, évolutive et haute performance. Parfaite pour les applications modernes avec des données non structurées et des schémas flexibles.',
    de: 'Dokumentenorientierte, skalierbare, leistungsstarke NoSQL-Datenbank. Perfekt für moderne Anwendungen mit unstrukturierten Daten und flexiblen Schemas.',
    it: 'Database NoSQL orientato ai documenti, scalabile e ad alte prestazioni. Perfetto per applicazioni moderne con dati non strutturati e schemi flessibili.',
    zh: '面向文档、可扩展、高性能的NoSQL数据库。非常适合具有非结构化数据和灵活架构的现代应用程序。',
    ja: 'ドキュメント指向、スケーラブルで高性能なNoSQLデータベース。非構造化データと柔軟なスキーマを持つ現代的なアプリケーションに最適。',
    ru: 'Документоориентированная, масштабируемая, высокопроизводительная база данных NoSQL. Идеально подходит для современных приложений с неструктурированными данными и гибкими схемами.',
    ar: 'قاعدة بيانات NoSQL موجهة للمستندات، قابلة للتوسع وعالية الأداء. مثالية للتطبيقات الحديثة مع البيانات غير المهيكلة والمخططات المرنة.',
    hi: 'डॉक्यूमेंट-ओरिएंटेड, स्केलेबल, हाई-परफॉर्मेंस NoSQL डेटाबेस। अनस्ट्रक्चर्ड डेटा और फ्लेक्सिबल स्कीमा वाले आधुनिक एप्लिकेशन के लिए परफेक्ट।',
    ko: '문서 지향, 확장 가능한 고성능 NoSQL 데이터베이스. 구조화되지 않은 데이터와 유연한 스키마가 있는 현대적인 애플리케이션에 적합합니다.',
    nl: 'Document-georiënteerde, schaalbare, high-performance NoSQL-database. Perfect voor moderne applicaties met ongestructureerde gegevens en flexibele schema\'s.',
    pl: 'Zorientowana na dokumenty, skalowalna, wysoko wydajna baza danych NoSQL. Idealna dla nowoczesnych aplikacji z nieustrukturyzowanymi danymi i elastycznymi schematami.',
    tr: 'Belge odaklı, ölçeklenebilir, yüksek performanslı NoSQL veritabanı. Yapılandırılmamış veriler ve esnek şemalarla modern uygulamalar için mükemmeldir.',
    hv: 'NoSQL vēttir sētagon se tembyr vestriagon. Tembyr hen ropagar sikagon se sikudeptor iderenigon.'
  },
  'Supabase': {
    es: 'Alternativa open source a Firebase con base de datos PostgreSQL, autenticación, almacenamiento y funciones serverless. Perfecta para desarrollo rápido de aplicaciones.',
    en: 'Open source Firebase alternative with PostgreSQL database, authentication, storage, and serverless functions. Perfect for rapid application development.',
    'en-us': 'Open source Firebase alternative with PostgreSQL database, authentication, storage, and serverless functions. Perfect for rapid application development.',
    'es-mx': 'Alternativa open source a Firebase con base de datos PostgreSQL, autenticación, almacenamiento y funciones serverless. Perfecta para desarrollo rápido de aplicaciones.',
    pt: 'Alternativa open source ao Firebase com banco de dados PostgreSQL, autenticação, armazenamento e funções serverless. Perfeita para desenvolvimento rápido de aplicações.',
    fr: 'Alternative open source à Firebase avec base de données PostgreSQL, authentification, stockage et fonctions serverless. Parfait pour le développement rapide d\'applications.',
    de: 'Open-Source-Alternative zu Firebase mit PostgreSQL-Datenbank, Authentifizierung, Speicher und serverlosen Funktionen. Perfekt für die schnelle Anwendungsentwicklung.',
    it: 'Alternativa open source a Firebase con database PostgreSQL, autenticazione, archiviazione e funzioni serverless. Perfetta per lo sviluppo rapido di applicazioni.',
    zh: '开源的Firebase替代品，具有PostgreSQL数据库、身份验证、存储和无服务器功能。非常适合快速应用程序开发。',
    ja: 'PostgreSQLデータベース、認証、ストレージ、サーバーレス機能を備えたFirebaseのオープンソース代替品。迅速なアプリケーション開発に最適。',
    ru: 'Альтернатива Firebase с открытым исходным кодом с базой данных PostgreSQL, аутентификацией, хранилищем и бессерверными функциями. Идеально подходит для быстрой разработки приложений.',
    ar: 'بديل مفتوح المصدر لـ Firebase مع قاعدة بيانات PostgreSQL، والمصادقة، والتخزين، والوظائف السحابية. مثالي للتطوير السريع للتطبيقات.',
    hi: 'PostgreSQL डेटाबेस, ऑथेंटिकेशन, स्टोरेज और सर्वरलेस फंक्शंस के साथ ओपन सोर्स फायरबेस विकल्प। रैपिड एप्लिकेशन डेवलपमेंट के लिए परफेक्ट।',
    ko: 'PostgreSQL 데이터베이스, 인증, 스토리지 및 서버리스 기능이 있는 오픈 소스 Firebase 대안. 빠른 애플리케이션 개발에 적합합니다.',
    nl: 'Open source Firebase-alternatief met PostgreSQL-database, authenticatie, opslag en serverloze functies. Perfect voor snelle applicatieontwikkeling.',
    pl: 'Alternatywa open source dla Firebase z bazą danych PostgreSQL, uwierzytelnianiem, przechowywaniem i funkcjami bezserwerowymi. Idealna do szybkiego tworzenia aplikacji.',
    tr: 'PostgreSQL veritabanı, kimlik doğrulama, depolama ve sunucusuz işlevlere sahip açık kaynaklı Firebase alternatifi. Hızlı uygulama geliştirme için mükemmeldir.',
    hv: 'Firebase iderenigon uēpa PostgreSQL vēttir, sȳndriorzir, vēttirdy, se hūchtys. Tembyr hen ropagar vestriagon.'
  },
  'GraphQL': {
    es: 'Lenguaje de consulta y manipulación de datos que permite a los clientes solicitar exactamente lo que necesitan. Alternativa eficiente a REST para APIs modernas.',
    en: 'Query and manipulation language for APIs that allows clients to request exactly what they need. Efficient alternative to REST for modern APIs.',
    'en-us': 'Query and manipulation language for APIs that allows clients to request exactly what they need. Efficient alternative to REST for modern APIs.',
    'es-mx': 'Lenguaje de consulta y manipulación de datos que permite a los clientes solicitar exactamente lo que necesitan. Alternativa eficiente a REST para APIs modernas.',
    pt: 'Linguagem de consulta e manipulação para APIs que permite aos clientes solicitar exatamente o que precisam. Alternativa eficiente ao REST para APIs modernas.',
    fr: 'Langage de requête et de manipulation pour les API qui permet aux clients de demander exactement ce dont ils ont besoin. Alternative efficace à REST pour les API modernes.',
    de: 'Abfrage- und Manipulationssprache für APIs, die es Clients ermöglicht, genau das anzufordern, was sie benötigen. Effiziente Alternative zu REST für moderne APIs.',
    it: 'Linguaggio di query e manipolazione per API che consente ai client di richiedere esattamente ciò di cui hanno bisogno. Alternativa efficiente a REST per API moderne.',
    zh: 'API的查询和操作语言，允许客户端请求他们确切需要的内容。对于现代API来说，是REST的高效替代方案。',
    ja: 'クライアントが必要なものを正確にリクエストできるAPIのためのクエリと操作言語。現代のAPIのための効率的なRESTの代替品。',
    ru: 'Язык запросов и манипуляций для API, который позволяет клиентам запрашивать именно то, что им нужно. Эффективная альтернатива REST для современных API.',
    ar: 'لغة استعلام ومعالجة لواجهات برمجة التطبيقات تتيح للعملاء طلب ما يحتاجونه بالضبط. بديل فعال لـ REST لواجهات برمجة التطبيقات الحديثة.',
    hi: 'API के लिए क्वेरी और मैनिपुलेशन लैंग्वेज जो क्लाइंट्स को वही मांगने की अनुमति देती है जो उन्हें चाहिए। आधुनिक API के लिए REST का कुशल विकल्प।',
    ko: '클라이언트가 정확히 필요한 것을 요청할 수 있는 API용 쿼리 및 조작 언어. 현대적인 API를 위한 REST의 효율적인 대안입니다.',
    nl: 'Query- en manipulatietaal voor API\'s waarmee clients precies kunnen aanvragen wat ze nodig hebben. Efficiënt alternatief voor REST voor moderne API\'s.',
    pl: 'Język zapytań i manipulacji dla API, który pozwala klientom żądać dokładnie tego, czego potrzebują. Wydajna alternatywa dla REST dla nowoczesnych API.',
    tr: 'İstemcilerin tam olarak ihtediklerini talep etmelerine olanak tanıyan API\'ler için sorgu ve işleme dili. Modern API\'ler için REST\'e verimli bir alternatiftir.',
    hv: 'Rhaenyrō gaomagon naejot laksir se tubis. Tembyr iderenigon hen REST naejot ropagar API.'
  },
  'MySQL': {
    es: 'Sistema de gestión de bases de datos relacional de código abierto ampliamente utilizado. Ideal para aplicaciones web con datos estructurados y relaciones complejas.',
    en: 'Widely used open-source relational database management system. Ideal for web applications with structured data and complex relationships.',
    'en-us': 'Widely used open-source relational database management system. Ideal for web applications with structured data and complex relationships.',
    'es-mx': 'Sistema de gestión de bases de datos relacional de código abierto ampliamente utilizado. Ideal para aplicaciones web con datos estructurados y relaciones complejas.',
    pt: 'Sistema de gerenciamento de banco de dados relacional de código aberto amplamente utilizado. Ideal para aplicações web com dados estruturados e relacionamentos complexos.',
    fr: 'Système de gestion de base de données relationnelle open source largement utilisé. Idéal pour les applications web avec des données structurées et des relations complexes.',
    de: 'Weit verbreitetes Open-Source-Relationales Datenbankmanagementsystem. Ideal für Webanwendungen mit strukturierten Daten und komplexen Beziehungen.',
    it: 'Sistema di gestione di database relazionale open source ampiamente utilizzato. Ideale per applicazioni web con dati strutturati e relazioni complesse.',
    zh: '广泛使用的开源关系数据库管理系统。非常适合具有结构化数据和复杂关系的Web应用程序。',
    ja: '広く使用されているオープンソースのリレーショナルデータベース管理システム。構造化データと複雑な関係を持つWebアプリケーションに最適。',
    ru: 'Широко используемая система управления реляционными базами данных с открытым исходным кодом. Идеально подходит для веб-приложений со структурированными данными и сложными отношениями.',
    ar: 'نظام إدارة قواعد البيانات العلائقية مفتوح المصدر المستخدم على نطاق واسع. مثالي لتطبيقات الويب ذات البيانات المنظمة والعلاقات المعقدة.',
    hi: 'व्यापक रूप से इस्तेमाल किया जाने वाला ओपन-सोर्स रिलेशनल डेटाबेस मैनेजमेंट सिस्टम। स्ट्रक्चर्ड डेटा और कॉम्प्लेक्स रिलेशनशिप वाले वेब एप्लिकेशन के लिए आदर्श।',
    ko: '널리 사용되는 오픈 소스 관계형 데이터베이스 관리 시스템. 구조화된 데이터와 복잡한 관계가 있는 웹 애플리케이션에 이상적입니다.',
    nl: 'Veel gebruikt open-source relationeel databasemanagementsysteem. Ideaal voor webapplicaties met gestructureerde gegevens en complexe relaties.',
    pl: 'Szeroko stosowany system zarządzania relacyjnymi bazami danych o otwartym kodzie źródłowym. Idealny dla aplikacji internetowych ze strukturalnymi danymi i złożonymi relacjami.',
    tr: 'Yaygın olarak kullanılan açık kaynaklı ilişkisel veritabanı yönetim sistemi. Yapılandırılmış veriler ve karmaşık ilişkiler içeren web uygulamaları için idealdir.',
    hv: 'Vēttir sētagon kostovon isse idereniby. Tembyr hen sikudeptor sikagon se mazmpār.'
  },
  'Strapi': {
    es: 'CMS headless de código abierto basado en Node.js que facilita la creación y gestión de APIs. Ideal para proyectos con arquitectura JAMstack y front-ends desacoplados.',
    en: 'Open-source headless CMS based on Node.js that simplifies API creation and management. Ideal for JAMstack architecture projects and decoupled front-ends.',
    'en-us': 'Open-source headless CMS based on Node.js that simplifies API creation and management. Ideal for JAMstack architecture projects and decoupled front-ends.',
    'es-mx': 'CMS headless de código abierto basado en Node.js que facilita la creación y gestión de APIs. Ideal para proyectos con arquitectura JAMstack y front-ends desacoplados.',
    pt: 'CMS headless de código aberto baseado em Node.js que simplifica a criação e gerenciamento de APIs. Ideal para projetos com arquitetura JAMstack e front-ends desacoplados.',
    fr: 'CMS headless open source basé sur Node.js qui simplifie la création et la gestion d\'API. Idéal pour les projets d\'architecture JAMstack et les frontends découplés.',
    de: 'Open-Source-Headless-CMS basierend auf Node.js, das die API-Erstellung und -Verwaltung vereinfacht. Ideal für JAMstack-Architekturprojekte und entkoppelte Frontends.',
    it: 'CMS headless open source basato su Node.js che semplifica la creazione e la gestione di API. Ideale per progetti con architettura JAMstack e frontend disaccoppiati.',
    zh: '基于Node.js的开源无头CMS，简化了API的创建和管理。非常适合JAMstack架构项目和解耦的前端。',
    ja: 'Node.jsに基づいたオープンソースのヘッドレスCMS。APIの作成と管理を簡素化します。JAMstackアーキテクチャプロジェクトと分離されたフロントエンドに最適。',
    ru: 'Бесплатная безголовая CMS с открытым исходным кодом, основанная на Node.js, которая упрощает создание и управление API. Идеально подходит для проектов с архитектурой JAMstack и отделенными фронтендами.',
    ar: 'نظام إدارة محتوى بدون واجهة مفتوح المصدر يعتمد على Node.js يبسط إنشاء وإدارة واجهات برمجة التطبيقات. مثالي لمشاريع هندسة JAMstack وواجهات أمامية منفصلة.',
    hi: 'Node.js पर आधारित ओपन-सोर्स हेडलेस CMS जो API क्रिएशन और मैनेजमेंट को सरल बनाता है। JAMstack आर्किटेक्चर प्रोजेक्ट्स और डीकपल्ड फ्रंट-एंड्स के लिए आदर्श।',
    ko: 'API 생성 및 관리를 단순화하는 Node.js 기반 오픈 소스 헤드리스 CMS. JAMstack 아키텍처 프로젝트 및 분리된 프론트엔드에 이상적입니다.',
    nl: 'Open-source headless CMS gebaseerd op Node.js dat API-creatie en -beheer vereenvoudigt. Ideaal voor JAMstack-architectuurprojecten en ontkoppelde frontends.',
    pl: 'Oparty na Node.js system zarządzania treścią bez interfejsu użytkownika typu open-source, który upraszcza tworzenie i zarządzanie API. Idealny dla projektów z architekturą JAMstack i oddzielonym frontendem.',
    tr: 'API oluşturma ve yönetimi basitleştiren Node.js tabanlı açık kaynaklı başsız CMS. JAMstack mimari projeleri ve ayrılmış ön uçlar için idealdir.',
    hv: 'CMS ropagar isse Node.js se māzigon API gaomagon. Tembyr hen JAMstack hūchtys udlissy.'
  }
};

export default backendDatabaseSkillDescriptions;