// Archivo de configuración para las descripciones de habilidades de frontend y herramientas
// Múltiples idiomas soportados

type SkillDescription = {
  [lang: string]: string;
};

type SkillDescriptions = {
  [skill: string]: SkillDescription;
};

export const frontendToolsSkillDescriptions: SkillDescriptions = {
  // Frontend frameworks y herramientas
  'Astro': {
    es: 'Framework web innovador que combina estáticos y dinamismo, optimizado para contenido con Islands Architecture. Ideal para sitios web rápidos y orientados al contenido.',
    en: 'Innovative web framework that blends static and dynamic capabilities, optimized for content with Islands Architecture. Ideal for fast, content-focused websites.',
    'en-us': 'Innovative web framework that blends static and dynamic capabilities, optimized for content with Islands Architecture. Ideal for fast, content-focused websites.',
    'es-mx': 'Framework web innovador que combina estáticos y dinamismo, optimizado para contenido con Islands Architecture. Ideal para sitios web rápidos y orientados al contenido.',
    pt: 'Framework web inovador que combina capacidades estáticas e dinâmicas, otimizado para conteúdo com Arquitetura de Ilhas. Ideal para sites rápidos e focados em conteúdo.',
    fr: 'Framework web innovant qui mélange capacités statiques et dynamiques, optimisé pour le contenu avec l\'Architecture Islands. Idéal pour les sites web rapides et axés sur le contenu.',
    de: 'Innovatives Webframework, das statische und dynamische Fähigkeiten verbindet, optimiert für Inhalte mit Islands Architecture. Ideal für schnelle, inhaltsorientierte Websites.',
    it: 'Framework web innovativo che combina capacità statiche e dinamiche, ottimizzato per contenuti con Architettura Islands. Ideale per siti web veloci e focalizzati sui contenuti.',
    zh: '创新的Web框架，融合了静态和动态功能，通过Islands Architecture优化内容。非常适合快速、内容为中心的网站。',
    ja: '静的および動的機能を融合させた革新的なWebフレームワーク。アイランドアーキテクチャによるコンテンツに最適化されています。高速でコンテンツ重視のWebサイトに最適。',
    ru: 'Инновационный веб-фреймворк, сочетающий статические и динамические возможности, оптимизированный для контента с использованием Islands Architecture. Идеально подходит для быстрых, ориентированных на контент веб-сайтов.',
    ar: 'إطار ويب مبتكر يمزج بين القدرات الثابتة والديناميكية، مُحسّن للمحتوى باستخدام هندسة الجزر. مثالي للمواقع الإلكترونية السريعة والتي تركز على المحتوى.',
    hi: 'इनोवेटिव वेब फ्रेमवर्क जो स्टैटिक और डायनामिक क्षमताओं को मिलाता है, आइलैंड्स आर्किटेक्चर के साथ कंटेंट के लिए ऑप्टिमाइज्ड। फास्ट, कंटेंट-फोकस्ड वेबसाइट्स के लिए आदर्श।',
    ko: '정적 및 동적 기능을 혼합한 혁신적인 웹 프레임워크로, 아일랜드 아키텍처로 콘텐츠에 최적화되어 있습니다. 빠르고 콘텐츠 중심의 웹사이트에 이상적입니다.',
    nl: 'Innovatief webframework dat statische en dynamische mogelijkheden combineert, geoptimaliseerd voor content met Islands Architecture. Ideaal voor snelle, content-gerichte websites.',
    pl: 'Innowacyjny framework webowy łączący możliwości statyczne i dynamiczne, zoptymalizowany dla treści z Architekturą Wysp. Idealny do szybkich, zorientowanych na treść stron internetowych.',
    tr: 'Statik ve dinamik yetenekleri harmanlayan, İzole Mimari ile içerik için optimize edilmiş yenilikçi web framework\'ü. Hızlı, içerik odaklı web siteleri için idealdir.',
    hv: 'Zyhossyr sikudeptor vestragon se tembyr. Tubis naejot sikudeptor tembyr.'
  },
  'Vite': {
    es: 'Herramienta de compilación frontend ultrarrápida basada en ES modules nativos. Ofrece desarrollo instantáneo en HMR y optimización de producción integrada para proyectos modernos.',
    en: 'Ultra-fast frontend build tool powered by native ES modules. Offers instant development with HMR and integrated production optimization for modern projects.',
    'en-us': 'Ultra-fast frontend build tool powered by native ES modules. Offers instant development with HMR and integrated production optimization for modern projects.',
    'es-mx': 'Herramienta de compilación frontend ultrarrápida basada en ES modules nativos. Ofrece desarrollo instantáneo en HMR y optimización de producción integrada para proyectos modernos.',
    pt: 'Ferramenta de compilação frontend ultrarrápida baseada em módulos ES nativos. Oferece desenvolvimento instantâneo com HMR e otimização de produção integrada para projetos modernos.',
    fr: 'Outil de construction frontend ultra-rapide alimenté par des modules ES natifs. Offre un développement instantané avec HMR et une optimisation de production intégrée pour les projets modernes.',
    de: 'Ultraschnelles Frontend-Build-Tool, das von nativen ES-Modulen angetrieben wird. Bietet sofortige Entwicklung mit HMR und integrierte Produktionsoptimierung für moderne Projekte.',
    it: 'Strumento di build frontend ultra-veloce alimentato da moduli ES nativi. Offre sviluppo istantaneo con HMR e ottimizzazione della produzione integrata per progetti moderni.',
    zh: '由原生ES模块驱动的超快前端构建工具。为现代项目提供即时开发（HMR）和集成的生产优化。',
    ja: 'ネイティブESモジュールを活用した超高速フロントエンドビルドツール。HMRによる即時開発と、最新プロジェクト向けの統合された本番最適化を提供します。',
    ru: 'Сверхбыстрый инструмент сборки фронтенда, работающий на нативных ES-модулях. Предлагает мгновенную разработку с HMR и комплексную оптимизацию производства для современных проектов.',
    ar: 'أداة بناء واجهة أمامية فائقة السرعة مدعومة بوحدات ES الأصلية. توفر تطويرًا فوريًا مع HMR وتحسين الإنتاج المتكامل للمشاريع الحديثة.',
    hi: 'नेटिव ES मॉड्यूल द्वारा संचालित अल्ट्रा-फास्ट फ्रंटएंड बिल्ड टूल। आधुनिक प्रोजेक्ट्स के लिए HMR के साथ इंस्टेंट डेवलपमेंट और इंटीग्रेटेड प्रोडक्शन ऑप्टिमाइजेशन प्रदान करता है।',
    ko: '네이티브 ES 모듈을 활용한 초고속 프론트엔드 빌드 도구. HMR을 통한 즉각적인 개발과 현대적인 프로젝트를 위한 통합된 프로덕션 최적화를 제공합니다.',
    nl: 'Ultrasnelle frontend-buildtool aangedreven door native ES-modules. Biedt directe ontwikkeling met HMR en geïntegreerde productie-optimalisatie voor moderne projecten.',
    pl: 'Ultraszybkie narzędzie do kompilacji frontendu, zasilane przez natywne moduły ES. Oferuje natychmiastowy rozwój z HMR i zintegrowaną optymalizację produkcji dla nowoczesnych projektów.',
    tr: 'Yerel ES modülleri tarafından desteklenen ultra hızlı frontend oluşturma aracı. Modern projeler için HMR ile anında geliştirme ve entegre üretim optimizasyonu sunar.',
    hv: 'Sikudeptor vestriagus tembyr tembyr isse ES magiaon. Tubis tembyr ropagon se vēttir.'
  },
  'Phaser': {
    es: 'Framework potente para desarrollar juegos HTML5 para navegadores móviles y de escritorio. Permite crear experiencias interactivas ricas con física, animaciones y sonido.',
    en: 'Powerful framework for developing HTML5 games for desktop and mobile browsers. Allows creation of rich interactive experiences with physics, animations, and sound.',
    'en-us': 'Powerful framework for developing HTML5 games for desktop and mobile browsers. Allows creation of rich interactive experiences with physics, animations, and sound.',
    'es-mx': 'Framework potente para desarrollar juegos HTML5 para navegadores móviles y de escritorio. Permite crear experiencias interactivas ricas con física, animaciones y sonido.',
    pt: 'Framework poderoso para desenvolver jogos HTML5 para navegadores desktop e móveis. Permite a criação de ricas experiências interativas com física, animações e som.',
    fr: 'Framework puissant pour le développement de jeux HTML5 pour navigateurs desktop et mobiles. Permet la création d\'expériences interactives riches avec physique, animations et son.',
    de: 'Leistungsstarkes Framework zur Entwicklung von HTML5-Spielen für Desktop- und Mobilbrowser. Ermöglicht die Erstellung reichhaltiger interaktiver Erlebnisse mit Physik, Animationen und Sound.',
    it: 'Potente framework per lo sviluppo di giochi HTML5 per browser desktop e mobili. Consente la creazione di ricche esperienze interattive con fisica, animazioni e suono.',
    zh: '用于为桌面和移动浏览器开发HTML5游戏的强大框架。允许创建具有物理、动画和声音的丰富交互体验。',
    ja: 'デスクトップとモバイルブラウザ向けのHTML5ゲーム開発のための強力なフレームワーク。物理、アニメーション、サウンドを備えた豊かなインタラクティブ体験の作成を可能にします。',
    ru: 'Мощный фреймворк для разработки HTML5-игр для настольных и мобильных браузеров. Позволяет создавать богатый интерактивный опыт с физикой, анимацией и звуком.',
    ar: 'إطار عمل قوي لتطوير ألعاب HTML5 لمتصفحات سطح المكتب والجوال. يسمح بإنشاء تجارب تفاعلية غنية مع الفيزياء والرسوم المتحركة والصوت.',
    hi: 'डेस्कटॉप और मोबाइल ब्राउज़र के लिए HTML5 गेम्स विकसित करने के लिए शक्तिशाली फ्रेमवर्क। फिजिक्स, एनिमेशन और साउंड के साथ समृद्ध इंटरैक्टिव अनुभव बनाने की अनुमति देता है।',
    ko: '데스크톱 및 모바일 브라우저용 HTML5 게임 개발을 위한 강력한 프레임워크. 물리, 애니메이션 및 사운드를 통한 풍부한 인터랙티브 경험을 제작할 수 있습니다.',
    nl: 'Krachtig framework voor het ontwikkelen van HTML5-games voor desktop- en mobiele browsers. Maakt het mogelijk om rijke interactieve ervaringen te creëren met natuurkunde, animaties en geluid.',
    pl: 'Potężny framework do tworzenia gier HTML5 dla przeglądarek stacjonarnych i mobilnych. Umożliwia tworzenie bogatych interaktywnych doświadczeń z fizyką, animacjami i dźwiękiem.',
    tr: 'Masaüstü ve mobil tarayıcılar için HTML5 oyunları geliştirmek için güçlü framework. Fizik, animasyonlar ve ses ile zengin etkileşimli deneyimler yaratılmasına olanak tanır.',
    hv: 'Zyhossyr tembyr hen HTML5 hāedri naejot vēttir se tubis. Sikagon gaomagon iderenigon isse physiks, uēpa, se dōbior.'
  },
  'C++': {
    es: 'Lenguaje de programación potente y de alto rendimiento con control de bajo nivel y funciones modernas. Utilizado en aplicaciones de sistemas, juegos y software que requiere velocidad.',
    en: 'Powerful, high-performance programming language with low-level control and modern features. Used in system applications, games, and software requiring speed.',
    'en-us': 'Powerful, high-performance programming language with low-level control and modern features. Used in system applications, games, and software requiring speed.',
    'es-mx': 'Lenguaje de programación potente y de alto rendimiento con control de bajo nivel y funciones modernas. Utilizado en aplicaciones de sistemas, juegos y software que requiere velocidad.',
    pt: 'Linguagem de programação poderosa e de alto desempenho com controle de baixo nível e recursos modernos. Usada em aplicações de sistema, jogos e softwares que exigem velocidade.',
    fr: 'Langage de programmation puissant et haute performance avec contrôle bas niveau et fonctionnalités modernes. Utilisé dans les applications système, les jeux et les logiciels nécessitant de la vitesse.',
    de: 'Leistungsstarke, hochperformante Programmiersprache mit Low-Level-Kontrolle und modernen Funktionen. Wird in Systemanwendungen, Spielen und Software verwendet, die Geschwindigkeit erfordern.',
    it: 'Linguaggio di programmazione potente e ad alte prestazioni con controllo di basso livello e funzionalità moderne. Utilizzato in applicazioni di sistema, giochi e software che richiedono velocità.',
    zh: '功能强大、高性能的编程语言，具有低级控制和现代功能。用于系统应用程序、游戏和需要速度的软件。',
    ja: '低レベル制御と現代的な機能を備えた、強力で高性能なプログラミング言語。システムアプリケーション、ゲーム、速度を必要とするソフトウェアで使用されます。',
    ru: 'Мощный, высокопроизводительный язык программирования с низкоуровневым контролем и современными функциями. Используется в системных приложениях, играх и программном обеспечении, требующем скорости.',
    ar: 'لغة برمجة قوية وعالية الأداء مع تحكم منخفض المستوى وميزات حديثة. تستخدم في تطبيقات النظام والألعاب والبرامج التي تتطلب السرعة.',
    hi: 'लो-लेवल कंट्रोल और आधुनिक फीचर्स के साथ शक्तिशाली, हाई-परफॉर्मेंस प्रोग्रामिंग लैंग्वेज। सिस्टम एप्लिकेशन, गेम्स और स्पीड की आवश्यकता वाले सॉफ्टवेयर में उपयोग होता है।',
    ko: '낮은 수준의 제어와 현대적인 기능을 갖춘 강력하고 고성능 프로그래밍 언어. 시스템 애플리케이션, 게임 및 속도가 필요한 소프트웨어에서 사용됩니다.',
    nl: 'Krachtige, hoogwaardige programmeertaal met lage-niveau controle en moderne functies. Gebruikt in systeemapplicaties, games en software die snelheid vereist.',
    pl: 'Potężny, wysokowydajny język programowania z kontrolą niskopoziomową i nowoczesnymi funkcjami. Używany w aplikacjach systemowych, grach i oprogramowaniu wymagającym szybkości.',
    tr: 'Düşük seviyeli kontrol ve modern özelliklerle güçlü, yüksek performanslı programlama dili. Sistem uygulamalarında, oyunlarda ve hız gerektiren yazılımlarda kullanılır.',
    hv: 'Kostōbi, tembyr rhaenyrō kodatys isse tubis control. Udlissy naejot gundytyr, hāedri, se vestriagus.'
  },

  // Herramientas de despliegue y gestión de paquetes
  'Vercel': {
    es: 'Plataforma de despliegue para proyectos frontend con CI/CD automático, serverless functions y CDN global. Ideal para sitios Jamstack, React, Vue y Next.js.',
    en: 'Deployment platform for frontend projects with automatic CI/CD, serverless functions, and global CDN. Ideal for Jamstack sites, React, Vue, and Next.js.',
    'en-us': 'Deployment platform for frontend projects with automatic CI/CD, serverless functions, and global CDN. Ideal for Jamstack sites, React, Vue, and Next.js.',
    'es-mx': 'Plataforma de despliegue para proyectos frontend con CI/CD automático, serverless functions y CDN global. Ideal para sitios Jamstack, React, Vue y Next.js.',
    pt: 'Plataforma de implantação para projetos frontend com CI/CD automático, funções serverless e CDN global. Ideal para sites Jamstack, React, Vue e Next.js.',
    fr: 'Plateforme de déploiement pour projets frontend avec CI/CD automatique, fonctions serverless et CDN global. Idéale pour les sites Jamstack, React, Vue et Next.js.',
    de: 'Bereitstellungsplattform für Frontend-Projekte mit automatischem CI/CD, serverlosen Funktionen und globalem CDN. Ideal für Jamstack-Sites, React, Vue und Next.js.',
    it: 'Piattaforma di deployment per progetti frontend con CI/CD automatico, funzioni serverless e CDN globale. Ideale per siti Jamstack, React, Vue e Next.js.',
    zh: '用于前端项目的部署平台，具有自动CI/CD、无服务器功能和全球CDN。非常适合Jamstack站点、React、Vue和Next.js。',
    ja: 'フロントエンドプロジェクト向けのデプロイメントプラットフォーム。自動CI/CD、サーバーレス機能、グローバルCDNを提供。Jamstackサイト、React、Vue、Next.jsに最適。',
    ru: 'Платформа развертывания для фронтенд-проектов с автоматическим CI/CD, бессерверными функциями и глобальным CDN. Идеально подходит для сайтов Jamstack, React, Vue и Next.js.',
    ar: 'منصة نشر لمشاريع الواجهة الأمامية مع CI/CD التلقائي والوظائف السحابية و CDN العالمي. مثالية لمواقع Jamstack و React و Vue و Next.js.',
    hi: 'फ्रंटएंड प्रोजेक्ट्स के लिए डिप्लॉयमेंट प्लेटफॉर्म जिसमें ऑटोमैटिक CI/CD, सर्वरलेस फंक्शंस और ग्लोबल CDN है। Jamstack साइट्स, React, Vue और Next.js के लिए आदर्श।',
    ko: '자동 CI/CD, 서버리스 기능 및 글로벌 CDN이 있는 프론트엔드 프로젝트를 위한 배포 플랫폼. Jamstack 사이트, React, Vue 및 Next.js에 이상적입니다.',
    nl: 'Deploymentplatform voor frontend-projecten met automatische CI/CD, serverloze functies en globale CDN. Ideaal voor Jamstack-sites, React, Vue en Next.js.',
    pl: 'Platforma wdrażania dla projektów frontendowych z automatycznym CI/CD, funkcjami bezserwerowymi i globalnym CDN. Idealna dla witryn Jamstack, React, Vue i Next.js.',
    tr: 'Frontend projeleri için otomatik CI/CD, sunucusuz işlevler ve küresel CDN ile dağıtım platformu. Jamstack siteleri, React, Vue ve Next.js için idealdir.',
    hv: 'Tubir urnen naejot sikudeptor ropagar isse tubos CI/CD se hūchtys. Tembyr hen Jamstack, React, Vue, se Next.js.'
  },
  'NPM': {
    es: 'Gestor de paquetes estándar para Node.js que permite compartir y reutilizar código. Facilita la gestión de dependencias y automatización del flujo de trabajo de desarrollo.',
    en: 'Standard package manager for Node.js that enables sharing and reusing code. Facilitates dependency management and automation of development workflow.',
    'en-us': 'Standard package manager for Node.js that enables sharing and reusing code. Facilitates dependency management and automation of development workflow.',
    'es-mx': 'Gestor de paquetes estándar para Node.js que permite compartir y reutilizar código. Facilita la gestión de dependencias y automatización del flujo de trabajo de desarrollo.',
    pt: 'Gerenciador de pacotes padrão para Node.js que permite compartilhar e reutilizar código. Facilita o gerenciamento de dependências e a automação do fluxo de trabalho de desenvolvimento.',
    fr: 'Gestionnaire de paquets standard pour Node.js qui permet de partager et de réutiliser du code. Facilite la gestion des dépendances et l\'automatisation du flux de travail de développement.',
    de: 'Standard-Paketmanager für Node.js, der das Teilen und Wiederverwenden von Code ermöglicht. Erleichtert die Abhängigkeitsverwaltung und Automatisierung des Entwicklungs-Workflows.',
    it: 'Gestore di pacchetti standard per Node.js che consente la condivisione e il riutilizzo del codice. Facilita la gestione delle dipendenze e l\'automazione del flusso di lavoro di sviluppo.',
    zh: 'Node.js的标准包管理器，可实现代码的共享和重用。便于依赖项管理和开发工作流程的自动化。',
    ja: 'Node.jsの標準パッケージマネージャーで、コードの共有と再利用を可能にします。依存関係の管理と開発ワークフローの自動化を容易にします。',
    ru: 'Стандартный менеджер пакетов для Node.js, который позволяет делиться и повторно использовать код. Облегчает управление зависимостями и автоматизацию рабочего процесса разработки.',
    ar: 'مدير الحزم القياسي لـ Node.js الذي يمكّن من مشاركة وإعادة استخدام الكود. يسهل إدارة التبعيات وأتمتة سير عمل التطوير.',
    hi: 'Node.js के लिए स्टैंडर्ड पैकेज मैनेजर जो कोड शेयरिंग और रीयूज़ को सक्षम बनाता है। डिपेंडेंसी मैनेजमेंट और डेवलपमेंट वर्कफ़्लो ऑटोमेशन को सुविधाजनक बनाता है।',
    ko: 'Node.js의 표준 패키지 관리자로 코드 공유 및 재사용을 가능하게 합니다. 종속성 관리 및 개발 워크플로 자동화를 용이하게 합니다.',
    nl: 'Standaard pakketbeheerder voor Node.js die het delen en hergebruiken van code mogelijk maakt. Vergemakkelijkt afhankelijkheidsbeheer en automatisering van development workflow.',
    pl: 'Standardowy menedżer pakietów dla Node.js, który umożliwia dzielenie się i ponowne wykorzystanie kodu. Ułatwia zarządzanie zależnościami i automatyzację procesu rozwoju.',
    tr: 'Kod paylaşımını ve yeniden kullanımını sağlayan Node.js için standart paket yöneticisi. Bağımlılık yönetimini ve geliştirme iş akışının otomasyonunu kolaylaştırır.',
    hv: 'Tembyr magiaon sētagon hen Node.js se sikagon idaña se udligon. Māzigon iderenigon tubos se ropagon.'
  },
  'PNPM': {
    es: 'Gestor de paquetes rápido y eficiente en espacio con almacenamiento de dependencias compartido. Alternativa a npm que optimiza el disco duro y mejora la velocidad de instalación.',
    en: 'Fast and disk space efficient package manager with shared dependency storage. Alternative to npm that optimizes disk usage and improves installation speed.',
    'en-us': 'Fast and disk space efficient package manager with shared dependency storage. Alternative to npm that optimizes disk usage and improves installation speed.',
    'es-mx': 'Gestor de paquetes rápido y eficiente en espacio con almacenamiento de dependencias compartido. Alternativa a npm que optimiza el disco duro y mejora la velocidad de instalación.',
    pt: 'Gerenciador de pacotes rápido e eficiente em espaço com armazenamento de dependências compartilhado. Alternativa ao npm que otimiza o uso do disco e melhora a velocidade de instalação.',
    fr: 'Gestionnaire de paquets rapide et économe en espace disque avec stockage de dépendances partagé. Alternative à npm qui optimise l\'utilisation du disque et améliore la vitesse d\'installation.',
    de: 'Schneller und platzsparender Paketmanager mit gemeinsamer Abhängigkeitsspeicherung. Alternative zu npm, die die Festplattennutzung optimiert und die Installationsgeschwindigkeit verbessert.',
    it: 'Gestore di pacchetti veloce ed efficiente nello spazio su disco con archiviazione delle dipendenze condivisa. Alternativa a npm che ottimizza l\'utilizzo del disco e migliora la velocità di installazione.',
    zh: '具有共享依赖项存储的快速且磁盘空间高效的包管理器。npm的替代品，可优化磁盘使用并提高安装速度。',
    ja: '共有依存関係ストレージを備えた高速でディスク容量効率の良いパッケージマネージャー。ディスク使用量を最適化し、インストール速度を向上させるnpmの代替品。',
    ru: 'Быстрый и эффективный по использованию дискового пространства менеджер пакетов с общим хранилищем зависимостей. Альтернатива npm, которая оптимизирует использование диска и повышает скорость установки.',
    ar: 'مدير حزم سريع وفعال في استخدام مساحة القرص مع تخزين اعتماديات مشترك. بديل لـ npm يحسن استخدام القرص ويحسن سرعة التثبيت.',
    hi: 'शेयर्ड डिपेंडेंसी स्टोरेज के साथ फास्ट और डिस्क स्पेस एफिशिएंट पैकेज मैनेजर। npm का विकल्प जो डिस्क उपयोग को अनुकूलित करता है और इंस्टॉलेशन स्पीड को बेहतर बनाता है।',
    ko: '공유 종속성 저장소가 있는 빠르고 디스크 공간 효율적인 패키지 관리자. 디스크 사용을 최적화하고 설치 속도를 향상시키는 npm의 대안입니다.',
    nl: 'Snelle en opslagruimte-efficiënte pakketbeheerder met gedeelde afhankelijkheidsopslag. Alternatief voor npm dat schijfgebruik optimaliseert en installatietijd verbetert.',
    pl: 'Szybki i wydajny pod względem miejsca na dysku menedżer pakietów z dzielonym przechowywaniem zależności. Alternatywa dla npm, która optymalizuje wykorzystanie dysku i poprawia szybkość instalacji.',
    tr: 'Paylaşılan bağımlılık depolaması ile hızlı ve disk alanı açısından verimli paket yöneticisi. Disk kullanımını optimize eden ve kurulum hızını artıran npm\'e alternatif.',
    hv: 'Tembyr se vēttir tembyr magiaon sētagon isse tubir iderenigon. Iderenigon naejot npm se māzigon vēttir udra.'
  },
  'Bun': {
    es: 'Entorno de ejecución JavaScript todo en uno extremadamente rápido con gestor de paquetes integrado. Optimizado para rendimiento y desarrolladores TypeScript.',
    en: 'All-in-one extremely fast JavaScript runtime with built-in package manager. Optimized for performance and TypeScript developers.',
    'en-us': 'All-in-one extremely fast JavaScript runtime with built-in package manager. Optimized for performance and TypeScript developers.',
    'es-mx': 'Entorno de ejecución JavaScript todo en uno extremadamente rápido con gestor de paquetes integrado. Optimizado para rendimiento y desarrolladores TypeScript.',
    pt: 'Ambiente de execução JavaScript tudo-em-um extremamente rápido com gerenciador de pacotes integrado. Otimizado para desempenho e desenvolvedores TypeScript.',
    fr: 'Runtime JavaScript tout-en-un extrêmement rapide avec gestionnaire de paquets intégré. Optimisé pour les performances et les développeurs TypeScript.',
    de: 'Extrem schnelle All-in-One-JavaScript-Laufzeitumgebung mit integriertem Paketmanager. Optimiert für Leistung und TypeScript-Entwickler.',
    it: 'Runtime JavaScript all-in-one estremamente veloce con gestore di pacchetti integrato. Ottimizzato per le prestazioni e gli sviluppatori TypeScript.',
    zh: '带有内置包管理器的极其快速的一体化JavaScript运行时。为性能和TypeScript开发人员优化。',
    ja: '内蔵パッケージマネージャーを備えた非常に高速なオールインワンJavaScriptランタイム。パフォーマンスとTypeScript開発者向けに最適化。',
    ru: 'Чрезвычайно быстрая универсальная среда выполнения JavaScript со встроенным менеджером пакетов. Оптимизирована для производительности и разработчиков TypeScript.',
    ar: 'بيئة تشغيل JavaScript سريعة للغاية متكاملة مع مدير حزم مضمن. مُحسّن للأداء ومطوري TypeScript.',
    hi: 'बिल्ट-इन पैकेज मैनेजर के साथ अत्यधिक तेज़ ऑल-इन-वन जावास्क्रिप्ट रनटाइम। प्रदर्शन और टाइपस्क्रिप्ट डेवलपर्स के लिए अनुकूलित।',
    ko: '내장된 패키지 관리자가 있는 매우 빠른 올인원 JavaScript 런타임. 성능 및 TypeScript 개발자를 위해 최적화되었습니다.',
    nl: 'Extreem snelle alles-in-één JavaScript-runtime met ingebouwde pakketbeheerder. Geoptimaliseerd voor prestaties en TypeScript-ontwikkelaars.',
    pl: 'Wyjątkowo szybkie, kompleksowe środowisko wykonawcze JavaScript z wbudowanym menedżerem pakietów. Zoptymalizowane pod kątem wydajności i programistów TypeScript.',
    tr: 'Yerleşik paket yöneticisine sahip son derece hızlı, hepsi bir arada JavaScript çalışma zamanı. Performans ve TypeScript geliştiricileri için optimize edilmiştir.',
    hv: 'JavaScript tubir tembyr tembyr isse vēttir magiaon sētagon. Ropagon tembyr se TypeScript vestriarzir.'
  },

  // Sistemas Operativos
  'Debian': {
    es: 'Distribución Linux libre y estable, base de muchas otras distribuciones populares. Conocida por su fiabilidad, gestión de paquetes robusta y compromiso con el software libre.',
    en: 'Free and stable Linux distribution, foundation of many other popular distributions. Known for reliability, robust package management, and commitment to free software.',
    'en-us': 'Free and stable Linux distribution, foundation of many other popular distributions. Known for reliability, robust package management, and commitment to free software.',
    'es-mx': 'Distribución Linux libre y estable, base de muchas otras distribuciones populares. Conocida por su fiabilidad, gestión de paquetes robusta y compromiso con el software libre.',
    pt: 'Distribuição Linux livre e estável, base de muitas outras distribuições populares. Conhecida por sua confiabilidade, gerenciamento robusto de pacotes e compromisso com software livre.',
    fr: 'Distribution Linux libre et stable, base de nombreuses autres distributions populaires. Connue pour sa fiabilité, sa gestion robuste des paquets et son engagement envers les logiciels libres.',
    de: 'Freie und stabile Linux-Distribution, Grundlage vieler anderer beliebter Distributionen. Bekannt für Zuverlässigkeit, robuste Paketverwaltung und Engagement für freie Software.',
    it: 'Distribuzione Linux libera e stabile, base di molte altre distribuzioni popolari. Nota per affidabilità, gestione robusta dei pacchetti e impegno per il software libero.',
    zh: '自由且稳定的Linux发行版，许多其他流行发行版的基础。以可靠性、强大的包管理和对自由软件的承诺而闻名。',
    ja: '無料で安定したLinuxディストリビューション、他の多くの人気ディストリビューションの基盤。信頼性、堅牢なパッケージ管理、フリーソフトウェアへのコミットメントで知られています。',
    ru: 'Бесплатный и стабильный дистрибутив Linux, основа многих других популярных дистрибутивов. Известен надежностью, надежным управлением пакетами и приверженностью свободному программному обеспечению.',
    ar: 'توزيعة لينكس حرة ومستقرة، أساس للعديد من التوزيعات الشهيرة الأخرى. معروفة بموثوقيتها، وإدارة الحزم القوية، والتزامها بالبرمجيات الحرة.',
    hi: 'फ्री और स्टेबल लिनक्स डिस्ट्रीब्यूशन, कई अन्य लोकप्रिय डिस्ट्रीब्यूशन की नींव। विश्वसनीयता, रोबस्ट पैकेज मैनेजमेंट और फ्री सॉफ्टवेयर के प्रति प्रतिबद्धता के लिए जाना जाता है।',
    ko: '무료이며 안정적인 리눅스 배포판으로, 다른 많은 인기 배포판의 기초입니다. 신뢰성, 강력한 패키지 관리 및 자유 소프트웨어에 대한 헌신으로 알려져 있습니다.',
    nl: 'Vrije en stabiele Linux-distributie, basis van veel andere populaire distributies. Bekend om betrouwbaarheid, robuust pakketbeheer en toewijding aan vrije software.',
    pl: 'Wolna i stabilna dystrybucja Linuksa, podstawa wielu innych popularnych dystrybucji. Znana z niezawodności, solidnego zarządzania pakietami i zaangażowania w wolne oprogramowanie.',
    tr: 'Özgür ve kararlı Linux dağıtımı, diğer birçok popüler dağıtımın temelidir. Güvenilirliği, sağlam paket yönetimi ve özgür yazılıma bağlılığı ile tanınır.',
    hv: 'Tubos se sȳndror Linux gundytyr, tubos hen tolmiot mazmagho. Lōgor hen sȳndrior, tembyr magiaon sētagon, se tubis naejot tubos software.'
  },
  'Kali': {
    es: 'Distribución Linux especializada en pruebas de penetración y auditoría de seguridad. Incluye cientos de herramientas preinstaladas para evaluación de seguridad y hacking ético.',
    en: 'Linux distribution specialized in penetration testing and security auditing. Includes hundreds of preinstalled tools for security assessment and ethical hacking.',
    'en-us': 'Linux distribution specialized in penetration testing and security auditing. Includes hundreds of preinstalled tools for security assessment and ethical hacking.',
    'es-mx': 'Distribución Linux especializada en pruebas de penetración y auditoría de seguridad. Incluye cientos de herramientas preinstaladas para evaluación de seguridad y hacking ético.',
    pt: 'Distribuição Linux especializada em testes de penetração e auditoria de segurança. Inclui centenas de ferramentas pré-instaladas para avaliação de segurança e hacking ético.',
    fr: 'Distribution Linux spécialisée dans les tests de pénétration et l\'audit de sécurité. Inclut des centaines d\'outils préinstallés pour l\'évaluation de la sécurité et le piratage éthique.',
    de: 'Linux-Distribution, spezialisiert auf Penetrationstests und Sicherheitsaudit. Enthält Hunderte von vorinstallierten Tools für Sicherheitsbewertung und ethisches Hacking.',
    it: 'Distribuzione Linux specializzata in penetration testing e audit di sicurezza. Include centinaia di strumenti preinstallati per la valutazione della sicurezza e l\'hacking etico.',
    zh: '专门用于渗透测试和安全审计的Linux发行版。包含数百种用于安全评估和道德黑客攻击的预装工具。',
    ja: '侵入テストとセキュリティ監査に特化したLinuxディストリビューション。セキュリティ評価と倫理的ハッキングのための数百の事前インストールされたツールを含みます。',
    ru: 'Дистрибутив Linux, специализирующийся на тестировании на проникновение и аудите безопасности. Включает сотни предустановленных инструментов для оценки безопасности и этичного взлома.',
    ar: 'توزيعة لينكس متخصصة في اختبار الاختراق وتدقيق الأمان. تتضمن مئات الأدوات المثبتة مسبقًا لتقييم الأمان والقرصنة الأخلاقية.',
    hi: 'पेनेट्रेशन टेस्टिंग और सिक्योरिटी ऑडिटिंग में विशेषज्ञता वाला लिनक्स डिस्ट्रीब्यूशन। सिक्योरिटी असेसमेंट और एथिकल हैकिंग के लिए सैकड़ों प्री-इंस्टॉल्ड टूल्स शामिल करता है।',
    ko: '침투 테스트 및 보안 감사에 특화된 리눅스 배포판. 보안 평가 및 윤리적 해킹을 위한 수백 개의 사전 설치 도구를 포함합니다.',
    nl: 'Linux-distributie gespecialiseerd in penetratietesten en beveiligingsaudits. Bevat honderden voorgeïnstalleerde tools voor beveiligingsbeoordeling en ethisch hacken.',
    pl: 'Dystrybucja Linuksa wyspecjalizowana w testach penetracyjnych i audytach bezpieczeństwa. Zawiera setki preinstalowanych narzędzi do oceny bezpieczeństwa i etycznego hackingu.',
    tr: 'Sızma testlerinde ve güvenlik denetiminde uzmanlaşmış Linux dağıtımı. Güvenlik değerlendirmesi ve etik bilgisayar korsanlığı için önceden yüklenmiş yüzlerce araç içerir.',
    hv: 'Linux gundytyr ubrardy hen urnen se sȳndrior. Tektol udlighelma udligon naejot sȳndrior jentys se ethical hacking.'
  }
};

export default frontendToolsSkillDescriptions;